### ISSUE TITLE
Use the original JavaScript object as the node.original property.

### ISSUE THREAD

**Issue by TMiguelT** [vakata/jstree#1005]
When using any of the methods of using JSON/JavaScript data to generate tree nodes (e.g. those described [here](http://www.jstree.com/docs/json/), accessing the node.original does not return the original object. The returned object has the same properties, but it does not have the same prototype or object name. This means that if the object is an instance of a JavaScript class/constructor, it won't be able to access its methods and it won't have a sensible name when debugging.

Here's a simple example as a jsFiddle: http://jsfiddle.net/8p5jtnsw/5/, and as raw code below. Basically in this example each node object has a `getChildren()` method that will return an array of nodes to use as its children. However the name of `node.original` is wrong and the prototype has been changed, meaning that this code throws an error *TypeError: parent.original.getChildren is not a function*, and the nodes never load. 

```html
<div id="tree"></div>
```

```javascript
//treeNode class 
function treeNode(val) {
    this.text = val;
    this.children = true;
}

//Return a child, one that is the square root, one that is the square
treeNode.prototype.getChildren = function () {
    return [
        new treeNode(Math.pow(this.val, 2)),
        new treeNode(Math.sqrt(this.val)),
    ];
}

$('#tree').jstree({
    'core': {
        'data': function (parent, callback) {
            //If it's the root node, give some starting numbers
            if (parent.id === "#")
                callback([
                    new treeNode(2),
                    new treeNode(3),
                    new treeNode(4),
                    new treeNode(5)
                ]);
            //Otherwise let the node genarate children for itself
            else
            {
                //The object name is wrong
                console.log(parent.original);
                //And the prototype methods aren't there
                callback(parent.original.getChildren());
            }
        }
    }
});
```

However if you move the method into the constructor function, everything works fine. Here's a [jsFiddle](http://jsfiddle.net/8p5jtnsw/4/)

**Comment by vakata** [comment]
Hi,

I get your idea, but that should be realized as plugin (or integrated in the core), using the `original` property will cause a lot of issues. 
The `node.original` property was never meant to be used the way you are trying to use it. It is a simple key value storage, and does not work well with anything other than plain objects. There are a number of reasons why the data is cloned and some properties are lost (as you noticed).

Your idea touches something completely different - using an object, which "implements" an interface and calling its methods in order to build and populate the tree. For example a simple interface would be `getChildren`, `hasChildren`, `getText`, `getID` (of course other plugins may need additional info like `getType`, `getIcon`, etc). The concept could be expanded by adding the ability to modify the model itself with a collection of `set*` methods.

This however is not on my todo list for now, I do not consider it a priority, and I am not even sure I will ever spend time building such a plugin. 

HOWEVER - you are more than welcome to provide a plugin / patch for this if you want and I will consider adding tweaking it and adding it to the core. You can have a look at the `src\misc.js` file for sample plugins. You will most likely need to override the `_load_node` / `load_node` functions.

Best regards,
Ivan

P.S. I will do some experimenting and I can share my findings and code with you if you want to build such a plugin.

**Comment by TMiguelT** [comment]
I'm willing to write a plugin/PR, although I do have some questions.

>The node.original property was never meant to be used the way you are trying to use it. It is a simple key value storage, and does not work well with anything other than plain objects.

Can you explain this a bit further? I get that you're cloning the object, but is there any reason `original` can't be a reference to the original object? After all it's not used internally, so why would that break anything?

>Your idea touches something completely different - using an object, which "implements" an interface and calling its methods in order to build and populate the tree.

This probably would make more sense because it would allow the JSON data to have nodes called `text`, `icon` etc. But this would break legacy code that used older versions of jsTree. Is this an issue?

**Comment by vakata** [comment]
I am almost done with a sample plugin - just give me a few minutes and we will be able to discuss directly in the code.

**Comment by vakata** [comment]
Here is the plugin along with a demo: http://jsfiddle.net/8p5jtnsw/7/

As for your concerns - including the plugin means that you wish to use such a model and therefore do not want to use the JSON / AJAX or function approach.

At the same time you can still have async data, as the getChildren method accepts a callback - so you can either use `return` or call the callback if you need async activity.

What needs to be added to the plugin is a function to allow passing more fields to the "normalized" JSON that jstree accepts (icon, type, li_arr, a_attr, etc) - jstree will check if a function on the model exists, if it does - it will pass in the "flat" object and will expect the function to return the modified object. 
Another approach would be to not use the standard jstree format at all, but that would mean an almost complete rewrite of all methods.

Best regards,
Ivan

**Comment by vakata** [comment]
The source is now in the repo - feel free to contribute ideas. Or if it satisfies your needs - to use it as is, the function that will be called on the object (if it exists) is `getExtra`.

Best regards,
Ivan

**Comment by TMiguelT** [comment]
Thank you! Although that example doesn't work for the `2` node because its id is 0, which I suppose you detect as falsy and generate an ID for it (`j1_1`) which breaks things. However if you start at 1 or use different ID logic it all works fine. I'll play around with it and see how it goes!
