### ISSUE TITLE
Fuzzy search is very inaccurate and produces false matches

### ISSUE THREAD

**Issue by aj-dev** [vakata/jstree#1036]
It appears that current implementation of fuzzy search in jsTree is flawed. Please see the screenshots bellow.

Incorrect matches using current master branch:
![wrong_match](https://cloud.githubusercontent.com/assets/2584733/6652050/35248452-ca60-11e4-862d-d099f589d6bf.png)

Correct matches after re-factoring the search logic:
![correct_match](https://cloud.githubusercontent.com/assets/2584733/6652052/3e68dcb6-ca60-11e4-8aa5-c1201614e5c4.png)

I have created plunkers for both and will link this issue to a pull request.
http://plnkr.co/edit/I8LoC7?p=preview
and
http://plnkr.co/edit/1AoWgh?p=preview

**Comment by vakata** [comment]
Thank you for the detailed report. 

Unfortunately what you implemented is not actually fuzzy search, I can not accept this pull request, as this would mean removing functionality. All that is needed is to raise the match threshold in the algorithm I am using. I will expose the algorithm options with the next commit, so that they are easily to modify.

As for the delayed search, I do not consider this a jstree responsibility, if someone wants to invoke search quickly it is a matter of 4-5 lines to implement a delay outside of jstree.

I will link to this ticket when I commit the exposed search options.

Best regards,
Ivan

**Comment by aj-dev** [comment]
Thanks for the explanation. I think I misunderstood the expected behaviour of fuzzy search in jstree and the fact that complete node text is highlighted made me think it was wrong.

Anyway, I'll try to play around with the exposed options and see if I can get desired results.

Do you have any plans to highlight only the matching substring, not the entire node name? So if I searched for **ny**, it would only highlight **n** and **y** in matching nodes.

**Comment by vakata** [comment]
No, not really, as especially with fuzzy search some characters from the search string may not be present in the node. However, I believe this could be easy to achieve if you need it - listen for the search `search.jstree` event, traverse the results (which you get in the handler) and highlight as necessary.

Best regards,
Ivan
