### ISSUE TITLE
jsTree drag & drop example does not work as expected

### ISSUE THREAD

**Issue by aj-dev** [vakata/jstree#1044]
Hi,

Your plugins example page (http://www.jstree.com/plugins/) is not using the latest master branch and drag & drop with multi-select does not work as expected. Only one of the dragged nodes is dropped in the right place. I could not reproduce this behaviour with the latest master code: http://plnkr.co/edit/I8LoC7?p=preview

![jstree_dnd_example](https://cloud.githubusercontent.com/assets/2584733/6686147/ff2152bc-cc9f-11e4-9880-bfac443412c0.gif)

Btw, when are you planning next release? It looks like there are quite a few significant bug fixes in master now.

**Comment by vakata** [comment]
Hi,

yes, this bug is fixed. I will release 3.1.0 as soon as I decide what to do with the `show_only_matches` open bug. I choose 3.1.0 as the search plugin has a few new options, and the `massload` plugin is added.
Unfortunately I have been a bit sick the last few days, so I did not have the chance to close the bug I mentioned above. I hope that I will later today or tomorrow.

Best regards,
Ivan

**Comment by aj-dev** [comment]
Thanks for the update. Looking forward to the new release!
