### ISSUE TITLE
Event binding after a destroy

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#1049]
I am loading JSTree along with JSTreeGrid on a button click. With each button click I want to refresh the same tree instance with new data. I have used `ready.jstree` for opening all loaded nodes and `loaded_grid` of JSTreeGrid for summing values from various columns in grid. Both the event handlers does not seem working after 
`$("#treeViewDiv").jstree('refresh');` 
or even after
`$("#treeViewDiv").jstree('destroy');` 

Hence after the first button click, the event handlers does not work. How I can I bind them again? 
This fiddle demonstrates the situation http://jsfiddle.net/gw9ch970/64/. 
Please help.

**Comment by vakata** [comment]
That is expected. 
`destroy()` removes all bound handlers - bind your handler again when you are creating the new instance. It is only logical to remove everything since you are destroying the instance. 

As for `refresh()` - there is no `ready` event triggered after refresh - there is a `refresh` event. You can easily listen for both with one handler - `.on("ready.jstree refresh.jstree", ...`.

Best regards,
Ivan

**Comment by MGenidy** [comment]
i have two tab its logic working on jstree first tab logic must work on jstree without plugins:[checkbox]
and second tab logic must work on jstree with plugins:[checkbox]
i destroyed the tree and rebuild it again with success of what plugins needed but all event not work else first time
