### ISSUE TITLE
Search plugin - no results message

### ISSUE THREAD

**Issue by aj-dev** [vakata/jstree#1059]
It's more a question and not an issue regarding search plugin.

Wouldn't it make sense to hide tree nodes when search returns no results with `$.jstree.defaults.search.show_only_matches = true`? Currently it shows all nodes even if there are no matches.

Also, how would you go about showing a 'no results' message in this case? Is there an elegant way to replace the contents of jsTree generated DOM or hide top level node and append custom element with message?

Thanks

**Comment by vakata** [comment]
You could use the `search.jstree` event - the reason behind this is that showing an empty container is even worse than showing all the nodes. So the best approach is to use the `search.jstree` event.

**Comment by jmayday** [comment]
In my case I used search function for quickfilter. In my approach filtering should pass no entries (nodes) at some point. 

`$('#mytree')
    .on('search.jstree', function(e, data) {
        if (data.res.length == 0) {
            $('#mytree').css("visibility", "hidden");
        } else {
            $('#mytree').css("visibility", "visible");
        }
    });`

Of course if you want to handle IE's clear button on input field (this small 'x') you have to remember about making tree visible just before calling search - I noticed that 'search.jstree' event is not triggered when calling search with undefined/empty string. Is it correct?

Ok, to wrap things up - I'm not sure if this is best way to achieve my goal, but also using `hide_all()` is not the best because at some point you have to make previously hidden nodes visible again.

**Comment by rogercoder** [comment]
@jmayday - Thanks!
I also added a div with a "No Results Found" message. Visibility is hidden by default, then shows whenever you hide jstree and vice-versa. Our customers expected the search to work like this ... the popular select list widgets (select2, etc) all seem to.

**Comment by jmayday** [comment]
@rogercoder "No Results Found" div is one of those small but nice additions which helps prevent user from being confused.

**Comment by MarceloFonseca** [comment]
Hello,

I've also implemented a "No results found" strategy, using a div, but i'm having some issues with the "$.jstree.defaults.search.show_only_matches" property, which although set to true when the tree is initialized, somehow it is not reflected after search.jstree event is handled - even if the handler does nothing.

**Comment by mikila85** [comment]
why not implement "No search results", it's a great idea and much needed, rather than messing with the event and add div .. 👎

**Comment by mikila85** [comment]
@vakata .. as @jmayday said: " 'search.jstree' event is not triggered when calling search with undefined/empty string"
so how are we suppose to implement this using your suggestion?
