### ISSUE TITLE
get_next_dom stopped working

### ISSUE THREAD

**Issue by somuelle-tmt** [vakata/jstree#1077]
I just updated from 3.0.1 to 3.1.0 and get_next_dom stopped working.

Here is a code snippet I'm using:
```javascript
var next_node = comptree.jstree(true).get_next_dom(last_marked_node);
```
In 3.0.1 I got the next node via next_quali[0], in 3.1.0 next_quali[0] is undefined.

Any ideas?

**Comment by vakata** [comment]
What is `next_quali`? Please provide some more context. 

Obviously `get_next_dom` works, because the keyboard shortcuts work just fine. Keep in mind it returns a DOM node, not a jQuery object, so the `[0]` part is probably the reason for the error.

For me to accept this as a valid ticket I need to be able to reproduce an issue - either provide a demo, or code, or detailed explanation and I will reopen this.

Best regards,
Ivan

**Comment by somuelle-tmt** [comment]
Sorry, I meant to write `next_node`!
I used `comptree.jstree(true).select_node(next_node[0])` to select it, works finde in v3.0.1.
If get_next_dom works, than I guess there is something that changed from v3.0.1 to v3.1.0. I'm looking through the commit, maybe you got an idea?

**Comment by vakata** [comment]
`get_next_dom` will only return visible nodes, that is by design. It changed a few versions back, so that keyboard shortcuts will work in a filtered tree view.

Best regards,
Ivan

**Comment by somuelle-tmt** [comment]
Ah, I get it, this makes sence if you have a filtered tree view.
But my tree is completely hidden, the nodes are all visible (theoretically). Would it be possible that you distinguish between this two conditions?

**Comment by vakata** [comment]
Sorry, I am afraid that is not possible. Or at least I can't think of a way.

**Comment by somuelle-tmt** [comment]
I've already done something like that by distinguishing between `ìf ( $('element:hidden') )=` and `if ( $(element).css('display') == 'none' )`

**Comment by vakata** [comment]
Unfortunately I doubt it will be that simple - the element may be hidden because it's parent is hidden, not because the actual element has `display:none`
