### ISSUE TITLE
edit() callback

### ISSUE THREAD

**Issue by alexandernst** [vakata/jstree#1087]
It would be nice to have a third parameter in the `edit()` method for a callback, instead of relying on the `rename_node` event.

**Comment by alexandernst** [comment]
Cool! :) Can you release a patch version of this in npm?

**Comment by vakata** [comment]
Thanks, it is reasonable to have that since it is an async event, here is an example of the usage:
```js
instance.edit('j1_1', null, function (node, status) { console.log(arguments); });
```
`node` is the renamed node, and `status` is the boolean status of the operation - `true` if the rename succeeded, `false` otherwise. To access the new title you can use `node.text`

Best regards,
Ivan

**Comment by vakata** [comment]
I will release a patch version in a day or two.

Best regards,
Ivan

**Comment by alexandernst** [comment]
@vakata new version ping :)

**Comment by vakata** [comment]
In a few days I guess - I am currently testing the performance impact of this:
https://github.com/vakata/jstree/blob/master/src/misc.js#L23

I am trying to determine if it should be a separate plugin, or added to core. As soon as I am done I will release 3.1.1

Best regards,
Ivan
