### ISSUE TITLE
problem with create_node

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#1096]
I would like to customize menu options under contextmenu by including only three options - create, rename and remove. I could get rename and remove functions working. But faces problem with create. Please see fiddle http://jsfiddle.net/gw9ch970/84/. 
I create a node under one parent node and switch to another parent to create a second node. Then previously created one is removed. 

What could be wrong?

**Comment by vakata** [comment]
Do not hardcode the IDs. You are creating a node with the same ID both times, the idea of the ID is to be unique, since you are creating two nodes with the same ID, there is a conflict and the second overwrites the first, and it causes problems with the internal structure.

To sum up - do not use the same ID - either omit the property or make sure it is unique.

**Comment by tharasp** [comment]
Thanks. updated fiddle. http://jsfiddle.net/gw9ch970/87/
