### ISSUE TITLE
jsTree with big sets of data

### ISSUE THREAD

**Issue by DanLawrence82** [vakata/jstree#1116]
Hello,

We've been using jsTree to help out in our programs with decent size lists. One of our client just gave us a list for the next set and its 16000+ items. On my pc jsTree loads it all up in a matter of 5-10 seconds (not bad). However I ran it on an older machine and we are looking at 20-30 seconds. We use the following code to initialize the tree:

                    this.ui.problemTree.jstree({
                        'plugins': ['wholerow', 'checkbox', 'search'],
                        'core': {
                            data: createJsonTree(this.collection)
                        },
                        'search': {
                            show_only_matches: true
                        }
                    });

Using jsTree is there a better way we can use jsTree to load and be able to search through the large dataset we have?

Thanks!

**Comment by vakata** [comment]
Try setting `core.worker` to `false` - it will block the UI, but it could be a good 40-50% faster.

Also - the best way to deal with large datasets is lazy loading, jsTree also supports server-side searches, so you should not worry about missing a result because of lazy loading. And even with lazy loading you can still load all needed nodes in a single request using the `massload` plugin, which means restoring state and searching will be fast, but they will not require the whole dataset to be on the client.

That being said, if lazy loading is not an option for you, maybe you can try removing the wholerow plugin and see if that makes a difference.

I am afraid there is no more tips I can give you, I have really worked hard on the performance of jsTree and right now I can not think of any other way to speed things up, so I will close this issue. But please do tell how each of the tips (aside from lazy loading) I gave above affected the performance of your tree.

Best regards,
Ivan
