### ISSUE TITLE
ready.jstree Issue

### ISSUE THREAD

**Issue by gauravjhs** [vakata/jstree#1119]
Sometimes ready.jstree event is not triggered, mostly noticed in Firefox.
It triggered as soon as I try to refresh the page.

**Comment by vakata** [comment]
Sorry, I will need a demo for this - I am using jsTree in more than 20 projects with various clients, and I have never noticed such a problem. 

Please create a demo of the problem so that I can see your config & data, as well as the jsTree version, only then will I be able to help. 

I will reopen the issue when you provide more information.

Best regards,
Ivan
