### ISSUE TITLE
QUESTION: Selected Items

### ISSUE THREAD

**Issue by DanLawrence82** [vakata/jstree#1138]
Hey Vakata,

Me again! The open_all did the trick. After testing the tree i noticed something and I don't know how to fix the issue. As you know i'm now using lazy loading for the children and the open_all when you check the parent when no children is loaded.

Take a look at the following screenshot: http://imgur.com/V82olGv

You will see that i have checked the header "Block R". That parent has 371 children underneath. Visually the tree says i have 3 selected. When i click the done button and use the get_bottom_selected function to get the checked values. I get all 371 records back. I have confirmed that the get_bottom_selected function is doing it and that all the nodes state -> selected value is true.

If i only check the three items under "Block R" and click done i'm getting the 3 items. Why is it when i click on the header its selecting them all? What am I doing wrong?

Thanks again!

**Comment by vakata** [comment]
Hi,

Sorry, but always include all the information necessary for me to help you - it is nothing personal - I believe only this week I answered more than a hundred separate questions, I am not sure I remember your use case. Also keep in mind it is best to ask how-to questions on the groups page or on stackoverflow with a `jstree` tag, and keep the repo issues page for things you suspect are a bug.

As for the issue - from what I can deduct you are using the search plugin with show_only_matches and are wondering why when you click the three separate children only they are selected, but clicking the parent will check everything beneath it, even non-matches? Is that it?

If so - that is the correct behavior - `show_only_matches` simply hides the other nodes, but they are still there. Selecting the parent will select them all - visible or not. Otherwise clicking the parent should move it in undetermined state, which will be even more confusing - there are countless use cases, where selecting only the three nodes, when the parent is clicked will be very bad UX. I get the problem, but I still believe this is the correct behavior - just think of the nodes are temporarily hidden but still there.

If this is not it, or if you have any ideas - please share.

Best regards,
Ivan
