### ISSUE TITLE
[BUG] HTML5 data-jstree "opened:false" is not respected

### ISSUE THREAD

**Issue by temuri416** [vakata/jstree#1156]
Hi,

http://jsfiddle.net/h6phbzd3/1/

1. Two nodes have ```data-jstree='{"selected":true}'```: "iPhone Original (EDGE)" and "iPhone 3GS".
2. All of their parents all the way to the top have ```data-jstree='{"opened":false,``` set.

Expected behaviour: nodes "iPhone", "iPhone 1", "iPhone 3GS" should be collapsed.
Actual behaviour: nodes "iPhone", "iPhone 1", "iPhone 3GS" are expanded.

Thanks!

**Comment by vakata** [comment]
There is no `opened:false` rule - all nodes are closed by default, you can use `opened` to explicitly open them. The problem you are having is that by default all selected nodes are revealed (their parents are opened), to prevent this from happening when the tree is ready use the `expand_selected_onload` config option:
http://www.jstree.com/api/#/?q=expa&f=$.jstree.defaults.core.expand_selected_onload

Here is the fixed demo (you may want to open the root though):
http://jsfiddle.net/h6phbzd3/2/

**Comment by temuri416** [comment]
So then, checked checkboxes override behaviour described at http://www.jstree.com/docs/html/:

```
You can also set the state on a node using a data-jstree attribute.
You can use any combination of the following: opened, selected, disabled, icon.
```

**Comment by temuri416** [comment]
Wouldn't it be easier for the user to allow use ```opened:false``` to avoid onload opening of nodes?

**Comment by vakata** [comment]
No, as this would lead to conflicts when traversing up and down. `opened` is designed to open nodes, by default they are closed - I think this is clear enough. 

The only time `opened:false` can be useful is your use case, which only exists because of selected nodes down the hierarchy and is solved by the `expand_selected_onload` setting. There would be no benefit in introducing one more option that does the same, but could also lead to a lot of conflicts when used.

Best regards,
Ivan

**Comment by temuri416** [comment]
Thanks for the explanation. No further questions.
