### ISSUE TITLE
JsTree gets error for certern json data

### ISSUE THREAD

**Issue by qq362220083** [vakata/jstree#1176]
Sample data like this:
```
[
    {
        "id": "node1", 
        "parent": "#", 
        "text": "Node1", 
        "children": true
    }, 
    {
        "id": "node11", 
        "parent": "node1", 
        "text": "Node 1-1", 
        "children": true
    }
]
```

jstree throws an exception:
```
Uncaught TypeError: m[dat[i].parent.toString(...)].children.push is not a function
```

**Comment by qq362220083** [comment]
I made a jsfiddler for this:  https://jsfiddle.net/m2pzftjx/

**Comment by vakata** [comment]
Only set `children : true` to nodes that you will be loading async. Since the children are already provided you must not set the children property to true: https://jsfiddle.net/m2pzftjx/1/

**Comment by jhonyourangel** [comment]
what if i need to set children to true ? because i have other children comming ?

**Comment by vakata** [comment]
Then just set it, do not do both. So if using the id / parent_id scheme, do not set `children : true` to the parent if you ahve already provided the children - just look at the examples.

If you mean that you want to "partially" load the children for a given parent and then load the rest - this is not possible.

Best regards,
Ivan

**Comment by jhonyourangel** [comment]
well i have a root from which i load async first level of children, then from those children, async load 3 lvl of children and so on.
I get the error on some specific data, but i can't figure out what is the problem.

the structure of data is always the same, and sometimes i get the error.

i use the scheme id / parent_id with ajax async calls.

How can i fix this ?
Is there another way to structure the json data so that won't crash the jstree ?

**Comment by vakata** [comment]
You probably have duplicated IDs.
FYI the id / parent_id has no problem with async calls, so that is not the reason for your problem.
If you load each batch of children separately you do not need the parent_id, but still - that is not an issue - I am almost certain that you have duplicated IDs, but I can't help you further without a demo.

Best regards,
Ivan

**Comment by jhonyourangel** [comment]
well, when i have duplicate ids, is just moving the children to the last ajax response. But in this case is not duplicate ids.

This is my data:

ParentID: N340A4891_1003251
ChildrenID: N34001896_1003251
GranSonID: N030BT999_1003251

And when the children becomes parent and ajax is sending the children, is giving me the error

`Uncaught TypeError: k[c[o].parent.toString(...)].children.push is not a function`

If i try to make the children (N34001896_1003251) root and start from it, is not working either.

I am pretty confident, that if you use those values, and give it a try you will have the same issue
