### ISSUE TITLE
Get synchronous refresh() back?

### ISSUE THREAD

**Issue by paulcrawls** [vakata/jstree#1187]
Hey,

I'm writing an app using jstree and came up with a problem.
Since after 3.0.1 refresh() method is asynchronous, I wonder how to work with several repeated calls of refresh().

In my case:
1) refresh() fired when jstree data is removed and cleaned up
2) and it's also fired when jtree data is updated from json

I read this: https://github.com/vakata/jstree/issues/866, but that particular example handles only the first call of 'changed.jstree' (with .one() method), while I need the second. I could have solved this with custom namespace, but it's already taken ('.jstree'). What to do? I need refresh() to only fire the second time.

Is there a way to get old refresh method back? Tried to extend refresh() and load_node() from 3.0.0, but it didn't help. 

Thanks for your answer!
Paul

**Comment by vakata** [comment]
What do you mean by asynchronous method? If your tree is not using async AJAX calls invoking `refresh` will refresh the tree immediately. There is no change in the method behavior. 

Provided you are not using async AJAX you can do something like this:
```js
$('#tree').jstree(true).refresh();
// tree is already refreshed
$('#tree').jstree(true).select_node('some-node-id');
```

If your data source is async (AJAX for example) use the `refresh.jstree` event - listen for it (on the instance's container) and react accordingly. 
Since you are calling `refresh` yourself you should be able to determine the cause of each refresh using some state variable in your application (from what I understand you need to know WHY you invoked it in the first place).

If neither the first or second solutions apply - please clarify.

Best regards,
Ivan
