### ISSUE TITLE
Searching for non-existing pattern shows all nodes instead of none

### ISSUE THREAD

**Issue by Fiedzia** [vakata/jstree#1192]
I'm settings show_only_matches to true. Entering phrase with matches limits
displayed nodes, but if the phrase is not present in any node,
suddenly jstree shows everything instead of nothing.

**Comment by vakata** [comment]
This is the intended behavior. 

A few months back if there are no matches jstree would hide everything. There were a lot of bug reports about it, so now jstree will not automatically hide the tree, as it turned out to be very confusing and inappropriate for most apps.

You can still hide everything of course - use the `search.jstree` event which will be fired with an empty result set - you can display a message, hide the tree, etc.

Best regards,
Ivan
