### ISSUE TITLE
Security: wrap json array in 'data'

### ISSUE THREAD

**Issue by ashl1** [vakata/jstree#1210]
The use of array on top of JSON response leads to security risk. Read more: http://flask.pocoo.org/docs/0.10/security/#json-security

I suggest to wrap the response array into ```data``` value so the response will be:

```
{
  'data': [
    // all arrays used in previous jstree version
  ]
}
```

And yes, it breaks old JSON format and requires to change server-side scripts.

**Comment by vakata** [comment]
I do not believe this is a valid issue. Saying not to use arrays as top level element when you are actually returning an array is absurd. Defending against this attack vector is the developer's job. Also as far as I can see this is fixed in ES5. 

If you are worried for your own project - there is an easy solution - set `core.data` to a function, make the request yourself and pass the `data` array back to jstree. You could also use jQuery's `dataFilter` option. So there you have it - two simple enough solutions if you are worried about this.

Best regards,
Ivan
