### ISSUE TITLE
jstree-context class not removed in some cases

### ISSUE THREAD

**Issue by tw3** [vakata/jstree#1227]
The jstree-context class seems to stick on a node if you right-click and it has no context menu.

**Comment by vakata** [comment]
Could you please provide steps to reproduce?

**Comment by tw3** [comment]
DEMO: http://www.tedweatherly.com/temp/jstree/jstree_sticky_context_menu/demo/sticky_context_menu/index.html

CODE: http://www.tedweatherly.com/temp/jstree/jstree_sticky_context_menu_code.zip

**Comment by vakata** [comment]
Oh, I see - you mean when the contextmenu is prevented - I will handle this. Thank you very much for the demo.

**Comment by tw3** [comment]
The contextmenu is not prevented...there is no contextmenu on purpose for the child nodes.  The code allows a contextmenu only for the root node on purpose.  This is not the bug:

if (jstNode.parent == '#') {
	// Context menu is only for root node
	menuItems = {
		folder: {
			label: "New Folder",
			action: function (menuItem) {
				console.log("Create new folder");
			}
		}
	};
}

The bug is that when there is no contextmenu and you right-click the node gets highlighted and stays highlighted.  The bug is that the node stays highlighted.

**Comment by vakata** [comment]
Yes, I understood that, sorry if I was not clear. I will fix it in jstree's code. Sorry if I gave you the impression that I did not understand what you mean. 
When the contextmenu is not shown jstree still highlights the node and then since the menu is never hidden (as it was never shown) the class stays in place - I will fix that.
