### ISSUE TITLE
render based on node count

### ISSUE THREAD

**Issue by kumar-abhisekh** [vakata/jstree#1240]
I have 100000 records , which i need to render on jstree. 
Rest API( return type JSON) can return record based on count Specified.
I am fetching first 1000 records on beforeOpen Event of Node.
Now I want to fetch next 1000 record once last node is browsed or loaded. Do we have such functionality

**Comment by vakata** [comment]
No sorry, paging is not possible - you can use lazy loading if data is deeply nested - if it is a large flat list - it is not possible to use paging, but if you have such a large flat list you probably do not need a tree component.

Best regards,
Ivan

**Comment by kumar-abhisekh** [comment]
Actually i want to display File System in a tree view which may have millions of files or folder under one node.

**Comment by vakata** [comment]
Short anwser is - you can't - it is not exactly a jstree limitation - it may work depending on the browser - most browsers simply can't handle the amount of DOM nodes necessary to render millions of jstree nodes in a flat list. Nested nodes will probably work fine, as jstree keeps only visible nodes in the DOM.

Flat lists may be possible if jstree supported paging - but that is not on my to-do list - sorry - it is way too isolated. I will probably add paging in version 4, which is only a concept now, I don't expect it to be ready earlier than 6 months form now.

Best regards,
Ivan

**Comment by ccarterc** [comment]
Perhaps a good compromise is to give the ability to add new nodes in batches instead of having to call "create_node" for every new node.  This will at least allow a user to load say the first 30 root elements on a single network call, and then follow up by adding 30 at a time.  Most modern browsers should support at least a thousand or so nodes in a list.  

One other alternative is to allow a large data set to be defined, but the "viewport" of the jstree determines how many of those data records have actual corresponding dom elements.  Basically an infinite scroll scenario, but loading new dom elements doesn't require necessarily a network call.

**Comment by vakata** [comment]
@ccarterc `create_node` is in no way related to this question - `create_node` should be used when the user creates nodes while interacting with the tree. There is a difference between loading and creating nodes. Thousands of nodes can be loaded in a single call.

As for rendering the nodes when they scroll into view - that is already a work in progress for v.4

**Comment by ccarterc** [comment]
@vakata Thanks for the quick reply.  I am currently working on a scenario where a single network call is not possible due to speed issues.  I am loading the first root 30 nodes with the first network call and then adding 30 at a time to the tree until it is all loaded: ~200 root nodes.  However after initial load and render, I couldn't find a way to add the additional nodes in a performant way. Any suggestions?

**Comment by eggersa** [comment]
I did implement a rather simple paging mechanism for my jsTree as I have about 6000 root nodes. Basically you can use any paging plugin of your choice (e.g. [jQuery simple pagination](http://flaviusmatis.github.io/simplePagination.js/)). Then simply pass the current page along with the data request. I trigger the refresh method of the jsTree each time a page has changed. Works like a charm.

**Comment by fralik** [comment]
@eggersa Do you mind sharing your solution?

**Comment by eggersa** [comment]
@fralik Basically that's all the details I can give you. I implemented everything with C# using Bridge.NET and created a custom wrapper for jsTree.

**Comment by peternoges** [comment]
I do the same as @eggersa, using java and jstree
