### ISSUE TITLE
how to add custom dom?

### ISSUE THREAD

**Issue by linjiazhen** [vakata/jstree#1249]
like them:
![123](https://cloud.githubusercontent.com/assets/1555132/10485211/888acae4-72bb-11e5-96ee-adf5a0a69021.png)

**Comment by vakata** [comment]
Please use the discussion group for how-to questions - this question has been answered several times.

As for the icons:
* if you need them for visualization only (no interaction) you can pass them in the node text as HTML
* otherwise (if you need interaction) this is best achieved with a plugin - you can check the `src/misc.js` file for example plugins

Best regards,
Ivan
