### ISSUE TITLE
Slow performance with 14000+ nodes in jsTree.

### ISSUE THREAD

**Issue by honey07** [vakata/jstree#1253]
Hi Ivan,

I am facing a performance issue right now. Recently I added around 14000 noded in jsTree (with checkboxes). 
I am keeping "three_state": false because I do not want each child node to be checked when parent gets checked. So, on the basis of my current requirement , I verify manually in the tree which child nodes I need to check and which not , when a parent nodes gets selected. This I am doing as follows:
 
```
.on('select_node.jstree', function (e, data) {
    for(var m=0;m<str.length;m++){
        var val = "#" + str[m];
        if(!$('#tree).jstree().is_disabled(val)) {
            $("#tree").jstree("check_node",val);
        }
    }
});
```

With 14000 nodes , its taking more than 1 minute (some time around 50 seconds at least) to check the complete tree when I check the root node (top most).

Please advise me on this as with this much time I will not be able to use jsTree.

Thanks.

**Comment by vakata** [comment]
Your code is very inefficient - do not use `#` - that makes jstree touch the DOM, which is not desired, you also seem to use the `$('#tree').jstree(` twice on each iteration - which again touches the DOM and is very inefficient (especially provided that you already have the instance available as `data.instance`).

Use the instance variable, also make use of the internal jstree storage, finally make sure you pass an array to `check_node`, so basically you need something like:

```
.on('select_node.jstree', function (e, data) {
    var model = data.instance._model.data,
          node = null, i, j, to_check = [];
    for(i = 0, j = str.length; i < j; i++){
        node = str[i];
        if (model[node] && !model[node].state.disabled) {
            to_check.push(node);
        }
    }
    data.instance.check_node(to_check);
});
```

This code is not tested, but it should get you going - keep in mind the problem was not in jstree itself, but in the way you are using it, and the way that you are using JS in general - read up on JS and DOM performance.

Best regards,
Ivan

**Comment by honey07** [comment]
HI Ivan,

Thanks a lot for pointing out the issues in my existing implementation. I have modified it as per your suggestion. Its working fine but still it takes around 40 seconds to check the complete tree. More over I observed different timings on IE9 and Firefox. For IE9 its 40 seconds and on Firefox its 15 seconds. Any specific reason for that?? 

Thanks,

**Comment by honey07** [comment]
Hi Ivan,

When tree is completely in the collapsed state, its taking less time to check the whole tree in comparison to the expended state. I am not able to understand this behaviour.

Thanks,
,

**Comment by cmscott2** [comment]
If you are still wondering about this all browsers implement code different, hence why some browsers load faster than others. Looking up the differences between the browsers performances might be useful for future use.  
For the collapsed state being faster, well that's because it doesn't have to update the UI as well.  Instead it only has to internally mark them as checked.
