### ISSUE TITLE
jstree does not appear to render when deployed on an IIS Server

### ISSUE THREAD

**Issue by palmeretp** [vakata/jstree#1254]
Hi,

The steps object is returned as a JSON object from the server. The code renders the tree fine when ran from visual studio, but not when deployed.  Wondering if this was encountered yet.

            $('#tSteps').jstree({
                'core': {
                    "theme": {
                        "variant": "large"
                    },
                    data: steps
                },
                "plugins": ["dnd"]
            });

        }

**Comment by vakata** [comment]
Sorry, I doubt this has something to do with jstree - provided the format is correct the tree will render.
Log out `steps` and see what it contains, also make sure `#tSteps` is available on the page when creating the tree (log it out too).

Best regards,
Ivan

**Comment by richbzb111** [comment]
Hi, I am using the demo on my localhost run as "http://localhost:64555/demo/basic/basic_mod1.html"--
I have two problems:
1st) I want to know what the heck this 
"$.get('?operation=get_content&id=' + data.selected.join(':'), function (d) {}" is?

Is that supposed to be getting .json data?  Where is the page that use that query "?operation=___&id=____ ?   Is it itself?
2nd)  if I run load your demo as php from your server, it's fine! But it would not work otherwise!
I hope you understand my questions.  Would like to hear your response, soon.

**Comment by vakata** [comment]
You can not run a PHP script as an HTML file - that is active server content, that needs a server side processor to do its job.

**Comment by richbzb111** [comment]
OK, thanks.

**Comment by anshu2kumar** [comment]
I have implemented jstree in my project and it is working fine (i.e rendering the tree ) on local machine but when it is deployed than it is just showing Loading...
Ionly two nodes I am creating but don't know what is the problem.
any help ? please

**Comment by anshu2kumar** [comment]
Uncaught ReferenceError: window is not defined
    at self.onmessage (84dfa4b4-3dbe-484e-acb2-4f18b0f2918b:1)
self.onmessage @ 84dfa4b4-3dbe-484e-acb2-4f18b0f2918b:1

this is the error only I am getting

**Comment by vakata** [comment]
This could be causes by a lot of things (configuration on your part), but the quick fix is to disable core.worker and try again.
