### ISSUE TITLE
Folders turn into leaves when no children exist

### ISSUE THREAD

**Issue by twh1808** [vakata/jstree#1258]
Inside of `load_node`, the following `if` block exists:
```
if(obj.state.loaded && !has_children && dom && dom.length && !dom.hasClass('jstree-leaf')) {
    dom.removeClass('jstree-closed jstree-open').addClass('jstree-leaf');
}
```
I believe this is strange behavior to have a folder turn into a leaf because no children existed. Our requirements is that a folder remains as is, simply with no children under it.

Is it possible to remove this, or add a configuration option to allow me to prevent the leaf flip? The only workaround I can think of is trying to flip it back after you've flipped it.

**Comment by vakata** [comment]
Please, do not use the internal classes for visualization purposes - my guess is your problem is you need a folder icon, not a leaf icon. But the purpose of the internal classes is different - please control visualization with other means (icon property, type property, etc). 

In computer science a tree node with no children is actuall a leaf node - that is the purpose of those classes, and they are needed by jstree internally.

Best regards,
Ivan
