### ISSUE TITLE
massload load twice

### ISSUE THREAD

**Issue by gitSquirel** [vakata/jstree#1261]
Hi Ivan,  I have a jstree using ajax search, it work fine, the ajax request return matched node's parent ids, the jstree load and open each of them. Then I think I can use then massload plugin to load them in one request, it also works, but when I inspect the network activity, I see the massload url was been loaded twice.

I have tried set the children and state property in the returned json to avoid this issue, but it doesn't work. I also find if I opened any node before search, this issue won't happen, in other words, this issue only happen when search before any node has been open.

Thank you for attention!

**Comment by vakata** [comment]
That is because with massload configured your "regular" data (the initial one for the tree) passes through massload (especially if you have the state plugin loaded). Do the two calls happen after searching? Could you please open the network panel while refreshing the page and confirm that the two calls only happen after searching, so that I can debug?

**Comment by gitSquirel** [comment]
Thanks for reply!

Yes, I am sure that the two call only happen after searching, and I didn't use the state plugin, also I didn't do anything to trigger the load_all event.

I find out that without massload, jstree load nodes more intelligent. If I return 5 node in search result, but if one or more of this 5 nodes has been loaded where I expand it manually, then jstree just load the rest of them one by one, ordered by the tree level; but with massload, it seems doesn't check which nodes has been loaded, just load all the nodes in search result.

**Comment by cvaida** [comment]
I may have some insight into massload issues.
First I will explain one cause everyone should check (at least until a fix is created). I store the path (IDs separated by /) for each node (it makes, for example, searching easier, as I only need to retrieve the path to know all parents - without consecutive database queries). I had a small error in the SQL query doing the paths update (when moving a node), which caused the path to not be updated properly.
As a result it was sending to jstree a node that jstree could not open so `this._data.massload` was not empty at the next search, and because of that (and the fact that jstree could not retrieve that node) it was falling back into `core.data()` calls. So I have added at the start of the `search` function `this._data.massload = {};` to reset the previously loaded data (because even after I fixed the path I did observe that after search is completed `massload()` is fired again twice, which again makes `this._data.massload` not empty). After that **hack** the search consistenly uses `massload()` rather than the `core.data()`.
I suppose that in the complete callback from `_load_nodes` this object should be emptied in case `delete this._data.massload[obj.id];` isn't performed on all returned data :)
But now I was left with the consecutive firing of the `massload()` after the initial one. So I figured something is wrong with `is_callback` because in massload plugin there is this:
`if(is_callback && !$.isEmptyObject(this._data.massload)) {`
so when it iterates through the results `is_callback` is **true** and the object is not empty, but when it finishes with the iteration the object **is empty** and `is_callback` is always true anyway, so the code below that is executed again until massload object is not empty. So after that if I wrapped the code below in `if(!is_callback) {` and changed the `is_callback` parameter on the search call to `_load_nodes` into false (so that at the initial call this code is executed), and now it all seems to work properly.
Sorry if I am not making myself clear enough :D it is a bit convoluted.

**Comment by cvaida** [comment]
This could be a temp solution, for me it works consistently.
Define a new *hack* plugin:
```
    $.jstree.plugins.reset_massload = function (options, parent) {
        this.reset_massload = function () {
            this._data.massload = {};
        };
    }
```
then make sure you define it in `plugins` as `'reset_massload'`, and then on the `search.jstree` event (fired after search is complete) add the reset call:
```
    .on('search.jstree', function (event, data) {
        data.instance.reset_massload();
    })
```
and now I always get one massload call every search.

**Comment by gitSquirel** [comment]
Thanks!
