### ISSUE TITLE
jsTree checkbox check_node is not working

### ISSUE THREAD

**Issue by MrChu** [vakata/jstree#1266]
# Tree
```js
$('#tree').jstree({
        'plugins': ["wholerow", "checkbox"],
        'core': {
                'themes': {
                        'icons': false
                },
                'data': [{
                        "text": "nodes",
                        "state": {"opened": true},
                        "children": [
                                {"text": "node01", "id": "01"},
                                {"text": "node02", "id": "02"},
                                {"text": "node03", "id": "03"}
                        ]
                }]
        }
});
```
# IE
## -_- check_node is not working
```js
var nodeids = ["01", "02"];
$("#tree").jstree(true).on("loaded.jstree", function (e, data) {
        $("#tree").jstree(true).check_node(nodeids);
}).jstree();
```
# Google or Firefox
## -_- check_node is not working
```js
var nodeids = ["01", "02"];
$("#tree").jstree(true).check_node(nodeids);
```
# So
```js
$(function () {
        checkTreeNodes("tree", "01");
        // checkTreeNodes("tree", ["01", "02"]);
});

/**
 * check tree node
 * treeid：tree id
 * nodeids：node id, id or id array
 */
function checkTreeNodes (treeid, nodeids) {
    // Tree
    var tree = $("#" + treeid);
    // IE
    tree.jstree(true).check_node(nodeids);
    // Chrome or Firefox
    tree.on("loaded.jstree", function (e, data) {
        tree.jstree(true).check_node(nodeids);
    }).jstree();
}
```
# Is this okay?

**Comment by vakata** [comment]
Check node is only available with `tie_selection` set to `false`. In your case - simply use `select_node` and use it in a "ready.jstree" event handler (not "loaded").

**Comment by MrChu** [comment]
Thank you very much, your avatar is so cool~

**Comment by cvaida** [comment]
In my opinion this behavior, strictly semantically speaking, is incorrect.
I understand the `tie_selection` and it makes perfect sense and it works great. Nothing to discuss about that. (Awesome refactoring from 1.xb to 3.x)
However calling the `check_node` method, one would, correctly, expect the `check_node.jstree` event to be fired after the call. The same applies with the `uncheck_node` method. Now, I agree with what you would say, that one should use `select_node` in this situation, but then why would we even have a `checkbox` plugin in this situation (since we are not using any of the specific checkbox methods or events)? Also consider that at some point, maybe it is desired that the `tie_selection` is disabled and set to `false`, so if one was using the `checkbox` related methods and settings, but, due to the fact that only the `select_node.jstree` and `deselect_node.jstree` were fired one was forced to use them, this setting change would break the application (if events were used of course). If also the `check_node.jstree` and `uncheck_node.jstree` were fired, then there would be no change required.
Now, I didn't really went through the code to see what actually happens with these events (internally) and if both of them can be called consecutively. But I think it would be more consequent if that would be possible.

PS: I actually was in this situation, but I figured out quite fast what I was doing wrong :)

**Comment by vakata** [comment]
Hello, 
I see your point, unfortunately such a major can change can happen only in v.4 (which is a work in progress). I will give your idea some thought and let you know.

Best regards,
Ivan

**Comment by asad-naeem** [comment]
Hi I reviewed my js and css file paths. Following are the files which should be referred:

<script src="~/Scripts/jstree.min.js"></script>
<script src="~/Scripts/jquery.scrollbar.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<link href="~/Contents/themes/default/style.min.css" rel="stylesheet"/>
