### ISSUE TITLE
Why is JSON data cloned during load?

### ISSUE THREAD

**Issue by ivolazy** [vakata/jstree#1323]

**Comment by ivolazy** [comment]
I have a JSON tree that loads from a database service and is used with D3 to visualize. When interacting between the jstree and the the D3 graph I'd like to be able to use the node objects, but it looks like during load the "original" attribute of the jstree nodes are set to clones of the original node objects and not the node objects themselves, which makes it hard to compare. I fixed it by adding another core settings parameter to skip the "parseJSON(stringify(...))" and "delete children" operations. 

Is there a good reason to be cloning the original nodes?

**Comment by vakata** [comment]
Not cloning the data caused a lot of issues for developers that wanted `refresh` to work in a way that it always restores data to the way it was. There was also a lot of confusion when people modified the object after passing it to jstree and then wondered why the structure changed. I will however add an option for this in v.4. Also keep in mind when using a function the data is not cloned, so that is a short way to deal with this without modifying the source.

Best regards,
Ivan
