### ISSUE TITLE
ajax search hits server but doesn't show result

### ISSUE THREAD

**Issue by mohammadaminalaee** [vakata/jstree#1327]
```
$('#node_tree').bind('loaded.jstree', function(e, data) {}).jstree({
            'core' : {
            'data': fill_tree(),
            'themes':{"icons":false}
        },
        "plugins": ["search", "state","themes"],
        'search': {
            'show_only_matches': true,
            'ajax': {
                'url': '/device/jstree',
                'method': 'GET',
                'dataType': 'JSON'
            }
        }
    });
```
I have used the above configuration and it works just fine with jstree default search. I have enabled ajax search, and it sends request to server as user types input, but the problem is jstree doesn't show my hard-coded result and is showing it's default search results. My hard-coded result is ["g-id"] and also tried ["#g-id"] but without any success.

**Comment by vakata** [comment]
What is "g-id"? It needs to be the ID of a node that needs to be opened, in order to reveal the match, NOT a result. AJAX search only makes sense in lazy loaded trees. It has nothing to do with what jstree considers a match - it will always use its own algorithm. In order to control what is considered a match you should use the `search_callback` config option.

Best regards,
Ivan
