### ISSUE TITLE
How to contribute!

### ISSUE THREAD

**Issue by tarungarg546** [vakata/jstree#1357]
How can we contribute to this library any how-to or specific guidelines we have to follow before making a pull request ?

**Comment by vakata** [comment]
No, not really. Unfortunately there are no tests yet, so just create the pull request and I will review it.

Just make sure you tested the code before requesting a pull, but I guess that goes without saying. If you are adding methods - make sure they have a doc block so that the API page will properly list them when the pull is merged.

Best regards,
Ivan
