### ISSUE TITLE
CSS before jstree finishes rendering

### ISSUE THREAD

**Issue by erez-o** [vakata/jstree#1358]
I'm rendering a tree with ~1000 leaves, read from the html, with the "wholerow" plugin.

Since it takes time for jstree to complete its rendering of the tree, it is noticeable that the tree is unstyled before the job is complete.

Is there any css class that can be added to the tree div (as in https://www.jstree.com/docs/html/), such that the tree will have an initial styling similar to how the tree will appear after jstree finishes running?

Thx for a great plugin

**Comment by vakata** [comment]
I will need a demo in order to help. Are you using raw HTML as input, and waiting for jstree to parse it? That is the only option to have unstyled content (I guess). If that is it - are you using the `worker` option? It should take parsing to a separate JS worker and leave the user with an empty DIV and a spinner - try that. 

As for classes - it would require a lot of those - I am not sure it will be a nice solution. However you can try something else - set a class to you DIV, for example `tree` and then use this css:

```css
.tree { display:none; }
.tree.jstree { display:block; }
```

This is a crude and untested example - you can of course substitute the `display:none` with something nicer.

Let me know if neither the worker, nor the CSS dirty fix work and I will reopen the issue. But please provide a little of you code - just a sample - the DIV, sample data, and how you configured jstree.

Best regards,
Ivan

**Comment by erez-o** [comment]
Thx Ivan, 

I am using the raw input and waiting for jstree to parse it.

I chose using html data because:
1. Let users that block js to view the tree's content.
2. Knowing that jstree can take time to complete, allow users to view the content before it does.

I'm not forced to using html data, I could have ajax the entire tree, or use json instead. I currently prefer the unstyled html. I thank you for the new solutions you suggested, but it's better to go with the ajax option. 

I think that a nice future feature of JStree would be to supply a css, given to the <div> class alone, and the tree would be styled before javascript, similar to how it would have been styled afterwards.

I don't know to what extent it is feasible, and I think its a huge effort of rewriting css code, so I don't know whether it's worth it, so I'm keeping this issue closed.

As to my setup, it's pretty standard:

I have several trees on the same page looking like this:

<div class="tree" id="tree1">
            <ul>
                <li id='i1' data-jstree='{"icon":"glyphicon glyphicon-list-alt"}' title="my title"><a href="/1"/>1</a></li>
                .... many more <li> + <ul> like these, different icons
          </ul>
</div>

<script>
    $(function(){
      $(".tree").jstree({
        "plugins" : [ "wholerow" ]
      });

       if ($('#tree1').length) {
        $('#tree1').jstree(true).select_node('i1');
        };

      $('.tree').on("changed.jstree", function (e, data) {
        window.location.href = data.node.a_attr.href
      });
    });
</script>



Thank you again for all your help.
