### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by CaptainMad** [vakata/jstree#1361]
No-thing
Not even the demo...
It's pathetic
such a great work

**Comment by vakata** [comment]
There are a lot demos here that work: https://www.jstree.com/demo/
And even more fiddles here: https://github.com/vakata/jstree

And among the users of jsTree are NASA, Oracle and a few governmental organizations - I would have heard from any of those if something (or rather nothing :) ) worked (because of their large user bases).

I can assure you everything works exactly as it is supposed to. Maybe you are doing something wrong. Unfortunately I can not help you as you are not giving me any information.

Best regards,
Ivan
