### ISSUE TITLE
Trigger an event if node has no children

### ISSUE THREAD

**Issue by Hemanth089** [vakata/jstree#1370]
I want to trigger an event irrespective of the node has child nodes or not. This is required to load some other ajax function.

I have a tree structure in parent nodes child nodes. If user expand a node it shows child nodes(using "open_node.jstree") in tree and parent node's files in another div(using another ajax call). But if the parent node has no children then "open_node.jstree" event is not firing.

Pl add support to trigger this ("open_node.jstree") event if no child node exists also.

**Comment by vakata** [comment]
I am sorry, but I will not add this. I am not sure I understand your idea. 

The `open_node.jstree` event will only fire if a node was opened. Since no node was opened (no children) it makes no sense to trigger such an event. There should also be no open node arrow next to a node with no children, so it should not even be possible to invoke `open_node` on such a node - maybe you are feeding the tree invalid data?

Either choose another event (like `load_node` / `select_node` / etc depending on your requirements), or attach your functionality to a regular DOM event.

Best regards,
Ivan

**Comment by Hemanth089** [comment]
Thank you for the info. The event I need is "load_node". This satisfies my need.
