### ISSUE TITLE
Enabling root folder : return error after 2º click on root (base folder)

### ISSUE THREAD

**Issue by vascomonteiro** [vakata/jstree#1374]
I need to enable root folder, to permit an update of possible data change.
1 Enabling root folder: OK
.on('model.jstree', function (nodes, data) { $('#tree').jstree("enable_node", "\/"); })

2 When i click in root folder 2 times (alternating or not with other folders) i get the error:
_TypeError: this._model.data[b.children_d[d]] is undefined_

What i am doing wrong? Thanks

**Comment by vakata** [comment]
This probably has nothing to do with enable/disable. You probably have duplicated IDs in the tree.
I am closing this for now as you have not included that data. I will reopen if you provide a demo of the error so that I have something to go on, as I can not reproduce it. Maybe create a jsFiddle?

Best regards,
Ivan
