### ISSUE TITLE
Add multiple childrens at once for performance improvement

### ISSUE THREAD

**Issue by gauravjhs** [vakata/jstree#1406]
Should be able to pass a JSON Array instead of JSON Object in create_node.

**Comment by vakata** [comment]
Sorry, `create_node` is only intended to be used as a result of client interaction, so it works only with a single node. Maybe you are confusing loading nodes with creating? Still, if you need to create multiple nodes - call `create_node` in a loop, that way you will have full control over the order of nodes being created.

Best regards,
Ivan

**Comment by gauravjhs** [comment]
Hi Ivan,
Thanks for your quick response. We are appending child on click of a node. There can be 5000 child for a particular node. There is a huge performance issue in this case.
Do you have a function for this kind of scenario?

**Comment by vakata** [comment]
From what I gather it seems to me you are mistaking creating nodes for loading nodes. Did you look at the native lazy loading option? Adding 5000 nodes using `create_node` is definitely not the way to go.

Best regards,
Ivan

**Comment by mmaunder** [comment]
Hi Ivan,

Can you be more specific? Calling create_node repeatedly is very slow for even 1000 nodes. How do you intend to have developers load e.g. 1000 nodes into an existing parent node in a tree? 

I can create a new node with 1000 children and that is very fast. But that does not help if you want to add 1000 children to an existing node. There does not seem to be any way to do this without repeatedly calling create_node which hangs the browser, probably due to redraws. 

I've examined your source and it looks like this is feasible, it's just not offered as a function as far as I can tell. I noticed you've played with setTimeout/clearTimeout in redraw() which is currently commented out to probably try to also fix this issue. I tried enabling that code and it didn't help make create_node faster. What did work for me is using the same technique and creating new nodes with several hundred children each and in that case redraw is only called once, and that was very fast and works great, but doesn't work for me because I need to append nodes to existing parents dynamically. 

Thanks,

Mark.

**Comment by MarceloFonseca** [comment]
Hello!

We are managing to use jstree in a large-scale application and we also came across with this problem.

Our workaround, which has proven to work well so far, was:

1. Keep the node where we wish to insert the big number of children;
2. Reset the children object of that node;
3. Remove the node from tree;
4. Re-insert it again, in the previous position, previously stored;

The node is immediately inserted, together with all children, performing a single redraw;

**Comment by vakata** [comment]
Hi @mmaunder & @MarceloFonseca 

Loading and creating nodes will use the same code in v.4, but in v.3 those are different concepts.
 
Until v.4 is out you can use `core.data` as a function (the most flexible data source anyway), which means calling `load_node` for any node will hit your function, which can return thousands of subnodes which will be displayed in a single redraw.

Best regards,
Ivan

**Comment by Llorx** [comment]
The thing is that, by user interaction, someone can create 1000 nodes on an already loaded node. The performance is very low in create_node with one or two hundred of children. I've noticed that when you call create_node, the engine redraws all the children the parent of the node has, resulting in a quite expensive call when the number of siblings increases.

**Comment by Llorx** [comment]
I've found 2 problems. One is that if you have sort enabled it will redraw everything two times and the other is that when you create a node, it recreates all siblings nodes each time.

This can be greatly improved by working directly on the `old` variable (moving positions with `insertBefore` and deleting non-existant) instead of moving nodes from `old` to `k`, but with this the idea is shown.

**Comment by VipinTiw** [comment]
Is this issue has been fixed and released in latest jsTree library.

**Comment by gs-rthati** [comment]
> Hello!
> 
> We are managing to use jstree in a large-scale application and we also came across with this problem.
> 
> Our workaround, which has proven to work well so far, was:
> 
> 1. Keep the node where we wish to insert the big number of children;
> 2. Reset the children object of that node, with all the new children structure;
> 3. Remove the node from tree;
> 4. Re-insert it again, in the previous position, previously stored;
> 
> The node is immediately inserted, together with all children, performing a single redraw;

Can you please add sample code?
