### ISSUE TITLE
Open parent onsearch

### ISSUE THREAD

**Issue by Joe312341** [vakata/jstree#1443]
Not sure if this is a bug or by design..if I search for a parent i cannot open that node

Example: Type in 'Fresh' and try opening the node

https://jsfiddle.net/txmed4aw/

Im using the cdns provided in the getting started section.

Thank you for your help

**Comment by vakata** [comment]
This is because none of the children match the search term, but you can set this config option to `true`:
https://www.jstree.com/api/#/?q=matches_children&f=$.jstree.defaults.search.show_only_matches_children

Here is the updated fiddle:
https://jsfiddle.net/txmed4aw/1/

Keep in mind I updated jstree to its latest version (you were using 3.0.9).

Best regards,
Ivan

**Comment by Joe312341** [comment]
Oh what confused me was that you have to put both

`show_only_matches` and `show_only_matches_children` to true,
I tried both but never in combination..thank you :)
