### ISSUE TITLE
error: get_json is not a function 

### ISSUE THREAD

**Issue by etproject** [vakata/jstree#1445]
in meteor, when i come first to the tab where jstree is defined, it works fine but when i change the tabs and come again to the jstree defined tab. I get this error.
`Uncaught TypeError: $(...).jstree(...).get_json is not a function`

I have also included setTimeout but getting same error.

**Comment by vakata** [comment]
Hi,

What does this code mean:
` $(...).jstree(...).get_json`

`jstree(...)` is used to create a tree, so the only acceptable replacement for `...` in this code is boolean `true` so that the already created jstree instance is returned. Otherwise you are recreating the tree on the already existing container. 

If you want to create an instance and then use `get_json` you will have to call only `get_json` in a timeout, or better - in a `ready.jstree` event handler.

I hope this helps, I can assure you this is not a problem with jstree.

Best regards,
Ivan

**Comment by etproject** [comment]
i am getting actually error fothis
$('#treeID').jstree().get_json is not a function.
it is working when the tab is visited 1st time, but when changing the tabs, it gives error.

i have also provided ready.jstree but still getting error

**Comment by vakata** [comment]
That means that the HTML is redrawn - the original node where you created a jstree instance is removed, and there is now a new node with the same ID there. This is something that can not be handled by jstree plugins - you have to work around this yourself (do not reload the tab HTML).

Best regards,
Ivan

**Comment by etproject** [comment]
got it. Thankyou. fixed the issue
