### ISSUE TITLE
jstree fails to load when child node is having special characters in name ,example  'test?'

### ISSUE THREAD

**Issue by kumar-abhisekh** [vakata/jstree#1449]
Console error: Failed to execute 'querySelector' on 'Element': '#\@\@\@\:\/test\/TestSlash\/Test?\/' is not a valid selector.

Can we have workaround for this.

**Comment by vakata** [comment]
Which jsTree version are you using? From what I can see the `:` is not escaped, but is explicitly handled in the latest code, so maybe you are using an older version.

If you are using the latest version and still get the error - please provide the actual ID you are trying to use.

Btw - the error is caused by IDs, not by the name - so please do not use the name as an ID, it will be better off to let jstree handle the IDs instead of assigning gibberish as an ID.

Best regards,
Ivan

**Comment by kumar-abhisekh** [comment]
Thanks a lot :-) , I have updated the library and it is working fine.
