### ISSUE TITLE
jstree fails to load when  node is having END OF TEXT '\u0003'

### ISSUE THREAD

**Issue by kumar-abhisekh** [vakata/jstree#1453]
Hi ,
I am able to show special character but for this '\u0003' I am getting error.
you can check this on fiddle  : https://jsfiddle.net/Abhisekh_kumar/v4vsffd0/2/

**Comment by vakata** [comment]
Sorry, but the error is a pure JS error: `"An invalid or illegal string was specified"` it is not generated by jsTree. The reason is the ID you are using - jstree uses those as keys of an object, so invalid strings can not be used. The `text` part will be fine, but take special care what you use as ID.

Best regards,
Ivan
