### ISSUE TITLE
No data, just "loading" in FireFox 47.0

### ISSUE THREAD

**Issue by nkolban** [vakata/jstree#1479]
I have a web app that is using jQuery, jQueryUI and jstree.

In my app, I make a REST call to retrieve data and then wish to draw the results in an existing jstree instance.

The API I am calling is

```
$("#entitiesTree").jstree(true).settings.core.data = treeNodes;
$("#entitiesTree").jstree(true).refresh();
```
The good news, it works perfectly in the latest Chrome and the latest Edge browsers ... however, in the latest FireFox, I get the "Loading ..." spinner ... and no tree.  I have validated that the data has been returned and the above two API calls are being made ... but that is as far as it goes.  No errors are being reported in the developer tools console and I am stuck on what to try next.

**Comment by vakata** [comment]
Does this work for you: http://jsfiddle.net/DGAF4/1415/ (as it does for me in Firefox)?

I can't help further, as I need a demo of the problem - the above fiddle was as close as I could get, and it works properly in all browsers for me.

Please provide a demo (or modify the above fiddle) and I will reopen the issue. If you can't provide a demo, nor create a similar fiddle where I can see the problem I really can't help. 

By the way - try recreating the tree and not modifying the settings at runtime. What you are doing is not officially supported and has never been tested (modifying the settings at runtime). The better way to do what you need would be to recreate the tree with the new data OR use `core.data` as a function which always returns a variable that you modify (instead of touching the internal `data` key).

Best regards,
Ivan

**Comment by nkolban** [comment]
Howdy Ivan,
I opened the fiddle supplied above ... and it too doesn't work on my FireFox.  All I see is the Loading message.  However, from your post you spurred me on to try more research ... I went over to a colleagues machine and opened up his FireFox and the jsfiddle worked perfectly.  Obviously this means that there is something screwy in my environment.  I will dig deeper and see if I can't find out what it might be as I try and run virgin browsers without plugins or customizations.   If it turns out to be something that others might run into, I'll post it back to this issue in case others may stumble upon it.

Again, I want to thank you for the awesome jstree.  It is working perfectly for me (on the other browsers) and is exactly what I needed ...

Neil

**Comment by kofifus** [comment]
I am having this exact issue as well (even with the fiddle above) .. just loading wheel but no data using chrome 52.0 

works fine on firefox.

Any help with this ?

**Comment by vakata** [comment]
I just tried with the latest Chrome (52) and it works fine, but sometimes the loading spinner takes too long to clear. Please try this fiddle and report any issues you may see in the dev console:
http://jsfiddle.net/DGAF4/1505/

**Comment by zvs001** [comment]
I had this issue in firefox. The problem was with worker.
It is start working when i disable him.
```
jstree({
  core: {
     data: [],
     worker: false
  }
});
```

**Comment by ckbizpart** [comment]
Setting worker to false fixed my issue with MS EDGE combined with callback method to set data. See here: http://jsfiddle.net/rpv9js35/

**Comment by umavaliya02** [comment]
jstree({
  core: {
     data: [],
     worker: false
  }
});
Worked for me. Thanks a ton!
