### ISSUE TITLE
changed.jsTree event fired twice if a node is already selected on a tree and the page re-loads

### ISSUE THREAD

**Issue by kwlshailesh** [vakata/jstree#1480]
changed.jsTree event fired twice if a node is already selected on a tree and the page re-loads

**Comment by vakata** [comment]
`changed` maybe triggered multiple times depending on your config, callbacks and data (state plugin, manual calls to select_node, state passed with the data, etc). 

This is no way wrong, I can't help you further unless you provide a full demo so that I can decide if it is a bug, or the normal flow of events.

I will reopen if you provide a demo and it is indeed a bug.

Thank you.
