### ISSUE TITLE
Dnd Event: Access Node Metadata

### ISSUE THREAD

**Issue by cwburggrabe** [vakata/jstree#1481]
Hey Vakata,

I started using your tree, and I love it over the alternatives.

I have a question about how to access a node's metadata when using the dnd.stop event. The other jstree.events have a "node" field already attached to the data object being passed back and the dnd events do not.

I was able to get the node by doing the following after dropping the tree item:

```
var jsonData = [
        "Child 1",
        {
            "id": "demo_child_1",
            "text": "Child 2",
            "children": [
                {
                    "id": "demo_child_2",
                    "text": "One more",
                    "type": "file",
                    "data": { id: 12344 }
                }
            ]
        }]
```

```
    function onDrop(e, data) {

        var node = data.data.origin._model.data[data.data.nodes[0]];

        console.log(node.data); // Prints { id: 12344 } in the console window
    }
```

Is there a easier way to access this or is this the only way?

Thank you in advance for your help!

**Comment by vakata** [comment]
Hi,

Yes - this is one way to get the data. The reason you are having so much trouble accessing it, is that `dnd_stop.vakata` is not a `jstree` event - it is fired from the DND helper, which is in no way limited to jstree, that is why there is no trace of jstree in the event properties. 

You need to listen for `move_node.jstree` and `copy_node.jstree` which will happen after dropping the node, or alternatively - attach a `check_move` callback which will be called before the move/copy operation is completed. I can not help further as I do not know what you are trying to achieve, but this should be enough to get you going.

There is nothing wrong with your approach of course, so it is fine to continue using it, since you already found a way to get the node data "manually". I just thought I'd explain why it was so hard to get it.

Best regards,
Ivan
