### ISSUE TITLE
keep drop area container the same height after first drop

### ISSUE THREAD

**Issue by prod1992** [vakata/jstree#1507]
Hey!

When I drop my node first time, the drop area is large. However when I try to drop second node into that area, I have to drop node near the first node. This is not user friendly, any solutions about this?

Thanks.

**Comment by vakata** [comment]
That is currently not possible, as there would be confusion regarding the position of the node - what if you drop at the top of the area, but since there are nodes already inside - the new node would be added to the bottom. I do not think position calculation is a good idea. 

Keeping the large drop target on the other hand will make it hard to cancel the drop, as a pixel or two away from any drop target inside the tree would trigger the large drop target, which will be confusing.

You can however attach your own handler and keep the large drop target if you will.

Best regards,
Ivan
