### ISSUE TITLE
get_top_selected is wrong

### ISSUE THREAD

**Issue by bondt** [vakata/jstree#1511]
In the API it says the following about `get_top_selected`:

> get an array of all top level selected nodes (ignoring children of selected nodes)

But that is not what it does. What it actually should say:

> determine the top most level of the selected nodes and return all selected nodes of only that level.

Is this a bug or just incorrect documentation?

I am looking for a way to find out if the _top most node_ is selected.

**Comment by vakata** [comment]
Sorry for the wording, `get_top_selected` will return all selected nodes, but not if they are a child of a selected node. I will think of a better way to describe it in the docs. 

As for your issue - why not get the node and check its state? `$('#tree').jstree(true).get_node('node_id').state.selected`

Since it is a top level node you could even do the check using the DOM - `$('#node_id').children('.jstree-node').hasClass('jstree-clicked')`

There are a few more ways to check, let me know if the above are not applicable.
