### ISSUE TITLE
Using jstree offline with IE11

### ISSUE THREAD

**Issue by Gargaroz** [vakata/jstree#1519]
Hi, I'm using jstree v3.2.1 wrapped with [ngJsTree](https://github.com/ezraroi/ngJsTree) in an AngularJS web-app to be used **mainly** on IE11 browsers.

I found that users who could not connect to the internet, due to their company policies, could not load properly the jstree I use within my forementioned web-app, on the other hand users who do access to the internet see everything just fine.

In particular the former users see just the spinner of jstree loading **frozen** and the "Loading..." text, which is strange because I set up the jstree config object to translate it into another string.

Moreover, I put a breakpoint inside the callback function associated to the ready event, and it never gets called.

Finally, the jstree part of my web-app works uber fine with both online and offline users when they reach it through Chrome or Firefox.

Is there any restriction on the online/offline usage of this library when in combo with some sort of IE11 strict security policy?

Thank you in advance

**Comment by vakata** [comment]
Unfortunately, I can't help you without a demo. I have not had any issues with IE11 and I am afraid there is nothing IE specific in the code. Have you tried creating a basic sample but without angular? There were quite a few issues caused by the angular wrappers (I am not saying this one is, but it is worth checking out).
Anyway - can you provide a demo so that I can try to help you?

**Comment by Gargaroz** [comment]
Thank you for your response.

As I explained, my observations point that this issue could be related to some kind of IE11 custom security policy set by the IT guys of the same company our users work for, so it's impossible for me to reproduce it.

But given that the wrapper works correctly in every browser of online users and just Firefox and Chrome for the offline ones, is there some IE11 custom security/privacy restriction which could harm something in jstree to a point where the spinner gif doesn't animate and the "Loading..." string is not switched with the string I provide within the config object?

**Comment by vakata** [comment]
This might seem a bit silly - but is there any console output? An error maybe? The only reason to be stuck at loading is a JS error. 

Since you said the spinner is not spinning - is the rest of the page responsive, as sometimes not spinning means excessive CPU usage?

The only thing I can think of that might violate policies is data URLs, but I doubt those are the issue. 

Have you tried using another data set - a single hard-coded node for example? I am asking because it might be something in the data?

As for not reading the translations in the config - that is very strange - it would indicate that the config is not read at all.

Best regards,
Ivan

**Comment by Gargaroz** [comment]
The problem is there's no JS error in the console, neither in network tab. The other parts of the web-app are working well.

For me it's quite difficult to create small tests, like the single hard coded node one you suggested, since it's a customer env.

I do find strange the config gets not read, even more strange is the fact that the ready callback gets not called too.
But tell me more about the data URLs you were talking about.

**Comment by vakata** [comment]
Check jstree's `style.css` for the `data` URLs - they are used for disabled nodes, striped background, etc. The other thing I would check in those offline users is compatibility mode - if IE is in quirks or compatibility mode jstree will not work.

Unfortunately, I do not see a way to further help you without some kind of additional info - it does not seem like an issue with jstree itself, but with some specific policies in IE. 

I will reopen if new information is available - in the mean time - we can continue the discussion of course.

Best regards,
Ivan

**Comment by lambert84** [comment]
We had the same problem with IE11 in an environtment without online access and custom security policies.
In our case the security policies somehow influenced the compatibility mode of IE which caused the problem.
After setting the compatibility mode manually in the Page header as described below everything works:
(After the Deployment we also needed to close and reopen the Browser, simply pressing refresh didn't change the compatibilty mode)

<html>
  <head>
 	<meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8;" />

**Comment by Gargaroz** [comment]
Thank you @lambert84 for delivering.

**Comment by Gargaroz** [comment]
Hi, I've been experiencing this issue again when I changed the meta tag delivered by @lambert84 into the following:

```html5
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge;"/>
```

I need this in order to fix an issue with another library, but this solution eventually breaks jsTree in the way we deeply discussed.
Can you please help me with that?
