### ISSUE TITLE
Edit mode enabled despite check_callback returning false

### ISSUE THREAD

**Issue by linkvt** [vakata/jstree#1535]
Hi,

we configured our jstree to have `check_callback` being set to a function, that contains some logic and returns true or false.
When modifying the tree e.g. by trying to create a node `check_callback` is evaluated correctly (see  [jstree.js#L3909](https://github.com/vakata/jstree/blob/master/src/jstree.js#L3909)).

The problem is, that the `check_callback` function isn't correctly evaluated when a node is in the edit mode - e.g. after pressing `F2` (see [jstree.js#L4347](https://github.com/vakata/jstree/blob/master/src/jstree.js#L4347)).

Just select the a node in this JSFiddle and press `F2`: http://jsfiddle.net/ee7f9f31/1/

Thanks!

**Comment by vakata** [comment]
This is by design - the function is not invoked on purpose. check_callback is not invoked when entering edit mode, only after exiting. The line you are pointing to is there to prevent edit mode when all changes are forbidden. If you want to prevent the tree from entering edit mode - you could blur the INPUT node as soon as it is focused or use a simple plugin that overrides the edit function with an empty one.
