### ISSUE TITLE
Get drop position in dnd_stop.vakata

### ISSUE THREAD

**Issue by LDSign** [vakata/jstree#1545]
Hi

How can I get the drop position in "dnd_stop.vakata" including if the drop is "on" a node or between two of them?

Thanks for your help,
Frank

**Comment by vakata** [comment]
The dnd_stop event is emitted from the helper DND library, which jstree uses, but is not aware of jstree's position helpers, so no - that is not possible. You need to use the move_node / copy_node events if you need the position.

**Comment by pemqs** [comment]
Hi.

What if I'd need to prevent the copy, in case the item is dropped in a certain jstree? imagine a case where I have 4 trees in my document, and I'm copying an element from tree 3 to tree 4, but if my account does not give me permissions to do so, I cannot have a valid drop happening, and need to be warned about that, therefore preventing the drop on the tree 4 and the removal from tree 3, how can I make this happen? what can I target in the jstree settings in order to set this?

Thanks in advance.
Pedro
