### ISSUE TITLE
I got an issue in both some lower version of IE11 and the lower version IE

### ISSUE THREAD

**Issue by ShadowWalker627** [vakata/jstree#1556]
The window.worker throw an error ---' security error' in line1853 of the jstree.js (version 3.3.2). This issue is just got in IE 11 and lower. Thanks

**Comment by vakata** [comment]
I can not help you without a demo - does it happen everywhere? Do you get the error on www.jstree.com or only on your page? If you get it only on your page there must be something wrong with the policies where you work or with your page (jstree will NOT work in quirks or compatibility modes - please check that). 
Please answer the above questions, if necessary create a demo and I will reopen. In the mean time - disable `core.worker` so that you have a working project.

**Comment by aadrian** [comment]
@vakata IMHO it should be a requirement when posting issues with "bugs" to provide a jsfiddle, or at least a link where this happens (e.g. main jstree.com site) . Even if it's not a bug, but the user has an "example" that it's not working as it's supposed to, a jsfiddle should still be a requirement.

**Comment by vakata** [comment]
@aadrian Couldn't agree more - I will focus on that soon - I will customize the issue tracker a bit.
