### ISSUE TITLE
Refresh_node freezes browser

### ISSUE THREAD

**Issue by guruas3** [vakata/jstree#1561]
I have a simple tree with ajax call to fetch data.
And when doing some actions to some nodes like rename or move i want to update db via ajax call and then refresh the node or parent node to fetch fresh data. But when i call `refresh_node({'id' : data.node.id})` and then trying to move children inside refreshed node the browser just freezes.
Here i made a jsbin example : http://jsbin.com/vuvupuduje/1/edit?html,js,console,output
Try renaming a node and then move/drag children inside. In jsbin it freezes just actions inside that node but in my app the whole window is freezed and i need to restart chrome.
I tried refresh_node as well as load_node. Same effect.
Thanks

**Comment by vakata** [comment]
Hi,

First of all, you are using an outdated version of jstree.
Secondly, you are using static data and trying to refresh a single node, what happens is that the whole data that you supplied is being fed into the single node leading to duplicate IDs and crashing. You can't refresh a single node when you have static nested data for the whole tree - the demo is wrong - there is actually nothing to refresh since this is static data.

Best regards,
Ivan

**Comment by guruas3** [comment]
I just showed a demo that i could do in jsbin. I have an API and on each action i call it through ajax. So when i call refresh in my application it actually makes another call to fetch json just for requested node.`'data' : {
                        'url' : '/product-categories',
                        'data' : function (node) {
                            return { 'id' : node.id };
                        }`
For example on rename i call through ajax my api and rename the name in db. then i call refresh for just renamed node and it calls my api and fetches json containing just that node and his children. After that i can't drag his children.

I'm using jstree through npm so it's the latest version.

Any thoughts what i'm doing wrong?

**Comment by vakata** [comment]
Please share a demo, or the responses of all ajax calls which jstree makes. Almost every issue regarding freezing is caused by duplicate IDs, also keep in mind refreshing a node refreshes its children, not the node itself. The node itself should not be in the response - if it is, then this is what causes the duplicated ID and the issue.

**Comment by guruas3** [comment]
Thank you very much! :+1: 
I excluded the node itself from the response and it's working great.

**Comment by brendon** [comment]
Even better, I'll answer my own question :D

Looks like I should have been using `tree.redraw(true)` instead after making those kinds of changes. `refresh_node()` is expecting a full node with children object to re-apply to the tree as far as I can see. As @vakata mentions, this makes no sense if we're dealing with a static tree with no way to fetch partial bits of the tree from the server.
