### ISSUE TITLE
Cannot render/load with children=>true

### ISSUE THREAD

**Issue by alan12111** [vakata/jstree#1567]
I have a JSON preloaded (root and one level after) and want to lazy load it when clicked so I added the attribute on the sublevels:
"children" : "true"

jsonObj.put("children", "true");

The preloaded tree nodes shows without the children:true but with children:true it will not render the preloaded data.

All nodes have the format:

{text: .. id: .. parent: ..}

For load i cannot get it to lazy load with setting children =>true, I have tried using json_data instead of core but no tree will show up.

     $('#tree').jstree({

                    'core': {

                        'data': x2, //preloaded data.. renders tree fine without adding children:true

                  //lazy load
                        "ajax": {

            "type": 'POST',

           

            "url":'myServlet',

            "data": {name: node.attr("id")},   //servlet accepts an Id and returns json

            "success": function (new_data) {

           

                return new_data;

            }

       	}

                      

                     }

             

                });

**Comment by vakata** [comment]
jsTree expects `core.data` to either be an array of objects, an AJAX config or a **function**. You need the last option - make sure you return your array of objects when jstree tries to load the root node and otherwise - make an AJAX call to your server. Using `core.data` as a function is documented and there is a demo on the homepage of this repo.

**Comment by alan12111** [comment]
It is returning an array of objects however the tree is not updating. am i missing a plugin?
