### ISSUE TITLE
How to refresh jstree when the underlying knockout observable arrays has been updated?

### ISSUE THREAD

**Issue by John1707** [vakata/jstree#1569]
HTML code:
```javascript
<div id="jstree_1">
    <ul data-bind="foreach: KoObservableArray">
        <li data-bind="attr: {type: type}">
            <a href="#" data-bind="text: text"></a>
            <ul data-bind="foreach: children">
                <li data-jstree='{"icon":"glyphicon glyphicon-leaf"}' data-bind="attr: {id: id, type: type}">
                    <a href="#" data-bind="text: text"></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
```

Then i will build the jstree with below command:
```javascript
$('#jstree_1').jstree({
    'plugins': ["wholerow", "checkbox"]
});
```

Everything works fine for first initialization.
After that, we update knockout observable array data (KoObservableArray), and we need to refresh the jstree to reflect the new data.

I tried:
```javascript
$('#jstree_1').jstree(true).refresh();
$('#jstree_1').jstree("refresh");
```

But none of them works for me. Please help and advices :(

Added example code for my problem.
http://jsfiddle.net/mang/pyh9m7de/7/

After click on changeMenu, I expect the jstree will be refresh to show the new data.

**Comment by vakata** [comment]
I do not use knockout so I am not sure how much I can help but here goes:

jsTree does not monitor the DOM for changes - when used with the HTML option (which btw I would only recommend for small trees) the DOM is parsed once into an internal structure and then all operations are performed on the internal structure.

The way to solve this issue is to make sure jstree loads its data from JSON and keep a reference to that object, modify as you please and call `refresh`. Here is a demo (without knockout): http://jsfiddle.net/pyh9m7de/9/

**Comment by John1707** [comment]
Thanks vakata for your reply.

I managed to solve this by re-assign the data to jstree.

$('#jstree_1').jstree(true).settings.core.data = self.array();
$('#jstree_1').jstree(true).refresh();
