### ISSUE TITLE
multiple choice tree issue

### ISSUE THREAD

**Issue by yotamm** [vakata/jstree#1580]
Hello,
loving the project, amazing work!
I used the tutorials on the overview and configuration tab to learn.
I noticed that if i initialize the tree to not allow multiple selection and using the select_node function the same as used in the tutorial, i can choose multiple items by marking an item and the button will mark another but not un-mark the first

`<script>
  $(function () {
    // 6 create an instance when the DOM is ready
    $("#jstree").jstree({
  "core" : {
    "multiple" : false,
    "animation" : 0
  }
});
    // 7 bind to events triggered on the tree
    $('#jstree').on("changed.jstree", function (e, data) {
      console.log(data.selected);
    });
    // 8 interact with the tree - either way is OK
    $('button').on('click', function () {
      $('#jstree').jstree(true).select_node('child_node_1');
    });
  });
  </script>`

**Comment by vakata** [comment]
Hi,

Thank you for the kind words.
Yes, that is by design - `select_node` is a "developer-level" method and is unaffected by the restriction, which applies to the end-user level method `activate_node`, so keep in mind jstree will not stop you the developer from selecting multiple nodes, only user interaction is prevented.

Best regards,
Ivan
