### ISSUE TITLE
Do not uncheck disabled nodes when Parent is unchecked

### ISSUE THREAD

**Issue by hmendezm** [vakata/jstree#1584]
I have a tree that the parent has disable and enable nodes. I need to keep always the disable nodes  with check and do not allow users to uncheck disabled nodes by unchecking the parent node. When users uncheck the parent node, the tree should uncheck only the enable nodes.

is a way to disable the parent node but keep the enable children?
Some idea how I can do this?

Best regards
H.

**Comment by vakata** [comment]
This has been discussed a lot in the groups page. Since there is no correct solution for this I will not be making changes to how jstree handles nested checkboxes and disabled nodes. There is simply no right solution. I believe some of the users on the groups page created plugins which handle this problem.
