### ISSUE TITLE
feature request: option to load all nodes before search

### ISSUE THREAD

**Issue by QueroBartK** [vakata/jstree#1586]
If I load my tree with ajax then not all nodes might be loaded as some are still closed and the children of those closed nodes will only be loaded when the nodes are opened. This might cause problems when searching on the tree (search is local and not with the ajax parameter) it will only search in the loaded nodes.

So I'm wondering if it is possible to have an option that when it is true checks if all nodes are loaded before searching in this case and if they are not, to load all nodes and only once all nodes are loaded search the nodes.

**Comment by vakata** [comment]
jstree supports server-based searching - it issues an AJAX request to a URL you specify with parameters you specify, the server returns an array of nodes to load in order to reveal the results. jsTree will handle this for you - it will load all the nodes and perform the search on the full set of data.
If you however still prefer to load all nodes, you can do that:
https://www.jstree.com/api/#/?q=load_all

Keep in mind that you can minimize the number of requests when loading batches with the `massload` plugin.

Best regards,
Ivan

**Comment by QueroBartK** [comment]
do you have an example of the ajax search?

Does the server get the current status of the tree and return the nodes based on this status or should it return each node from root to target node?
