### ISSUE TITLE
add extra icon in jstree node to display the add,delete node option

### ISSUE THREAD

**Issue by srinadh14** [vakata/jstree#1588]
Hi,

I observed that  couldn't add new extra icon to node element.I required this because i have scenario which 
forces me to create add extra icon or image at the end of each node element.if the user clicks on it i need to show the options like add node,delete node,update node .

Please suggest me how to achieve this requirement.

**Comment by aadrian** [comment]
> Please suggest me how to achieve this requirement.

We use the https://github.com/deitch/jstree-grid plug-in to display an extra column with info, and also an "Actions" column with the operations you mention.

**A.** If you only need the "Actions" column, than you can style the grid to have invisible lines (so that the actions would be aligned but look as if belonging to each node).

**B.** An even more user friendly approach to A. would be to hide the actions by default, and only if the mouse is hovering over the tree to display them. This makes the tree more readable, but might bring some problems if your application must implement accessibility too.

**Comment by vakata** [comment]
The proper way to do this would be to create a plugin. Take a look at any of the plugins that modify the default markup for a node (like checkbox or wholerow) - you can add your button using the `redraw_node` function and add event handlers in the `bind` function of your plugin.

Best regards,
Ivan
