### ISSUE TITLE
Error while selecting nodes

### ISSUE THREAD

**Issue by donandre** [vakata/jstree#1631]
Hello. I have an error, while changing nodes: 
TypeError: this._data.core.last_clicked.state is undefined (jstree.min.js:3:9609)

ways to reproduce:
1) open 1-st root tree
2) select (click on) child of 1st root 
3) open 2nd root tree 
4) select (click on) child of 2nd root 
4) select (click on) child of 3rd-st root 
5) open 3rd root tree 
7) close 1st root tree
8) open 1st root tree
error blocks opening of trees, which were opened  before
May be smth wrong with my tree creation parameters/data structure? please, see attachment (server.js called tree.html. root/child data in *.json files) 

error text from browser:
a.jstree.core.prototype.activate_node()    jstree.min.js:3
a.jstree.core.prototype.bind/<()   jstree.min.js:2
.proxy/e()   jquery.js:2
m.event.dispatch()   jquery.js:3
m.event.add/r.handle()   jquery.js:3

[jstree.zip](https://github.com/vakata/jstree/files/597648/jstree.zip)

**Comment by vakata** [comment]
Hi, this is because you are using lazy loading in the wrong way - you can't load children of different parents in a single request (as you are trying to do). What happens is that every time a root node is opened a new AJAX request is made, which messes up the internal ID structure, as the received data contains children of multiple root nodes.
