### ISSUE TITLE
"Unique" plugin rename node to an existing name. 

### ISSUE THREAD

**Issue by ibtest** [vakata/jstree#1648]
I'm using `jstree` with `unique` plugin. When I rename a file using a new name that already exists this will result in a name of "New node (n)" format which is correct behavior but the event "rename_node.jstree" is never emitted. I found the piece of code which is causing this (dist/jstree.js) and I changed that part a little bit and it seems to work but I would like to know if there is a more elegant solution for this.

Thanks,
Valeriu.

**Comment by vakata** [comment]
I don't think this can happen - can you provide a demo? The only time a string can be appended to the node name is when a node is CREATED, not renamed (unless there is a bug I can't reproduce).
If that is what happens - there is no need to fire the ```rename_node``` event, as the ```create_node``` event is fired and in that event you get the actual name (with the suffix). 
Let me know if I misunderstood something.

**Comment by narinearraul** [comment]
Hi @vakata,

I am having a similar problem. I need to catch the moment this happens so I can do error handling. I thought of overriding `$.jstree.defaults.unique.duplicate`  in my code but doesn't seem to work. I have example code in this stack overflow question: http://stackoverflow.com/questions/35785566/replacing-the-duplicate-function-for-the-unique-plugin

Is there a more straight forward way of catching when a user enters a duplicate node and add code if so?

**Comment by vakata** [comment]
Yes - you can set the duplicate function in your jstree config and not by replacing the defaults. Keep in mind you might also want to set core.data to a function that returns your variable, and then skip recreating the tree in your update method and use `refresh`.

**Comment by chrisadamsonmcri** [comment]
Hi @vakata ,

I'm having the same issue. I want to introduce error handling for duplicate matches after rename. But instead of creating a unique, hardcoded name like "New Node (...)" I want the node name to stay editable and put up an error message. Can I use the  the duplicate function in the jstree config to do this?

Could you give an example of where to put the function in the jstree config?
Failing this, if I remove the unique plugin jstree does allow me to rename a node using the same text as an existing node. But in the rename_node.jstree callback it has also changed the id to reflect the new text. In this case, is it possible to change the text and id of the renamed node and enable editing?

Thanks in advance.
