### ISSUE TITLE
Checkbox accessibility.

### ISSUE THREAD

**Issue by JackDarth** [vakata/jstree#1667]
Hi

The aria-label on `<a />` tag got read when I check the checkbox, but the aria-label on `<a />` tag do not read when I uncheck the checkbox.

I change the `<a />` tag aria-label every times when the user check/uncheck the checkbox.  So the accessibility screen reader can pick up and read the aria-label in `<a />`.  Screen reader read the aria-label when I check the checkbox successfully but it do not read when I uncheck the checkbox.  Please help.

```
$('#data').on('deselect_node.jstree', function (e, data) {
	$('#'+data.node.a_attr.id).attr('aria-label', document.getElementById(data.node.a_attr.id).text + ' uncheck');
	$('#'+data.node.a_attr.id).attr('aria-checked', 'false');
});

$('#data').on('select_node.jstree', function (e, data) {
	$('#'+data.node.a_attr.id).attr('aria-label', document.getElementById(data.node.a_attr.id).text + ' check');
	$('#'+data.node.a_attr.id).attr('aria-checked', 'true');
});
```

**Comment by vakata** [comment]
Sorry, I am afraid I can't help you. I simply do not know when the reader is supposed to pickup the changes. This is the best I can do about accessibility. Btw, the screen reader should probably be able to pickup the state from the attributes (active, activedescendant, selected, etc), there should not be a need to change the label.

I am afraid I can't help you further. But if you find some information on how to improve accessibility - please share so that I can implement.
