### ISSUE TITLE
Repeat delete after event error

### ISSUE THREAD

**Issue by gromo89** [vakata/jstree#1694]
I develop application in which js tree is used to manage some tree structure. On tree events I perform some AJAX requests and if action is prohibited for some reason - (in my app you cannot delete non empty nodes) I show some error message and refresh tree (loaded via AJAX).
My problem is that after failed attempt to delete non empty node event all future attempts to delete node trigger "delete_node.jstree" event for node that I want to delete and all nodes for which attempt failed.
Only solution I found so far is to reload page.

**Comment by vakata** [comment]
I am afraid this is not a problem with jstree - jsTree will only trigger a `delete_node.jstree` event after a node is deleted. 
The only thing I can think of is if you are deleting a selected node via a user interaction, in which case all selected nodes are deleted (which is by design). But that would mean that your `refresh` call was not OK.

Basically - I can only help if you provide a demo of the issue. Please provide more info and I will reopen.
