### ISSUE TITLE
Search by id

### ISSUE THREAD

**Issue by dzemba1986** [vakata/jstree#1699]
Hi,
I try to search (ajax) by id. For example when I run get request:
http://....index.php?id=1
I would like to search node whose id = 1 and after select it.

Currently I have something like this:

$("#device_tree").on(
            "ready.jstree",
            function(e, data) {
            	data.instance.search("OWW2/50");      //search by text not id       
            }
);
$('#device_tree').on('search.jstree', function (e, data) { data.instance.select_node(data.res); });

**Comment by vakata** [comment]
Hi,

ajax search is only meant to tell jstree which nodes need to be opened in order to reveal the matches. The actual matching is done on the client and by default uses the node text content. If you want to control what is considered a match take a look at the docs for `search_callback`

Best regards,
