### ISSUE TITLE
Jstree search takes more time IE 11 and blocks any other user operation from being triggered

### ISSUE THREAD

**Issue by abdulsmrehman** [vakata/jstree#1723]
Hi All,

Currently we are facing issue with jstree search only in IE.There are 2 parts for this issue

Issue 1: Search is taking lot of time when compared to chrome and firefox. 

Issue 2: When tree-search is happening , we are not able to acess any other part of application, The application is like in forzen state.

We are using this flag also as true "show_only_matches" . Is there any way to increase the performance of jstree search in IE.

Thanks in Advance
Abdul Rahaman

**Comment by vakata** [comment]
There is no hidden way to make this faster on IE, I am constantly trying to improve performance, but it all depends on the size of the tree, the search results count, and of course - the jsTree version you are using. If you are not using the latest version - please upgrade.

As for improving - disabling show_only_matches will speed things up, if fuzzy searching is enabled - you could disabled it.

I am closing this for now, but please let me know your jstree version and node count, sharing your jstree config would also be great, so that I can debug this. I will reopen on more information.
