### ISSUE TITLE
select_node it´s called twice

### ISSUE THREAD

**Issue by alanTorresManci** [vakata/jstree#1726]
Whenever the select_node method is triggered it does the content twice, how can I avoid that?
Here´s an example of my code:
![screen shot 2017-03-15 at 18 33 54](https://cloud.githubusercontent.com/assets/12723030/23976547/053a0e58-09ae-11e7-81ac-dca9da9c5da5.png)

**Comment by alanTorresManci** [comment]
@vakata I just noticed that it´s not only the select_node event, this happens in all events

**Comment by vakata** [comment]
Could you provide a demo? A jsFiddle perhaps? I am absolutely certain that events do not fire twice. Did you make sure you are not binding your handlers twice? I am closing this until a demo is available.

Here is a demo of the select_node event firing once - feel free to modify it so that I can see the problem: 
http://jsfiddle.net/DGAF4/2022/

**Comment by alanTorresManci** [comment]
I was putting everything inside `angular.element(document).ready(function () {});`
Apparently that causes the error, I removed it and it´s working marvelously, thanks!
