### ISSUE TITLE
drag'n'drop move

### ISSUE THREAD

**Issue by fearrr** [vakata/jstree#1753]
Hello.
It's about drag'n'drop transfer.
I use nestedset and when I move from one parent to another, it is not enough for me to know the index inside the parent to keep the node in the desired position, I need to know what node will stand after it or if after no node is inserted into the end.
Please tell me how to get the ID of the subsequent node when moving drag'n'drop?

**Comment by vakata** [comment]
One of the PHP demos uses a nested set - you can check there for inspiration. 
It should be more than enough to know the parent and index in order to place the node. To answer your question - the node that will stand after the moved node is the one which currently occupies the same position you are moving to. That being said - you are free to use the DOM (or jstree's helper methods) to find the next node when `move_node.jstree` fires and pass the ID along with the other data - something like:
`var next = data.instance.get_next_dom(data.node, true); if (next) { /* next.attr('id') */ }`
