### ISSUE TITLE
No input for rename when create node.

### ISSUE THREAD

**Issue by MehdiBela** [vakata/jstree#1814]
Hello and first of all, thank you for your work. 

I've an issue when creating new nodes with create option in context menu. If I'm right, default behavior should be to open a text input so that user can give a name to the new node. My issue is that I don't have this input.
 I've a function to allow rename on double click, but I'd really like to also have the expected behavior. I've read a lot of topics of people trying to disable it, but none about this issue. I saw that in precedent versions there was a 'skip_rename' option but I guess it has been removed so I can't have interfere with it.

I've actually no idea what causes this, I've tried to give no default name when creating an element, but then nodes just have 'New node' for name and there's still no input to rename it.

Thanks in advance for any suggestion.

**Comment by vakata** [comment]
Here is a demo:
http://jsfiddle.net/2kwkh2uL/6283/

If you right click the node and choose create, then a node is created and an input shown.
Maybe you missed the ```check_callback``` part? 

If this does not help - please modify the fiddle so that I can reproduce the problem, let me know, and I will reopen this issue.

Best regards,
