### ISSUE TITLE
Browser eats RAM. How destroy jstree instance correctly?

### ISSUE THREAD

**Issue by Zlatov** [vakata/jstree#1870]
(Reopen [572](https://github.com/vakata/jstree/issues/572))

Let me talk with the code:
```
var panel = $('#panel')
var struct = panel.children('#one_tree')
struct.jstree({core:{data: ... }, ...})
```
Now the user does not want a tree:
```
struct.jstree(true).destroy()
panel.empty()
panel.append(another_html)
```
Then user want tree:
```
panel.empty
panel.append(<div id="struct...)...
struct = $(...
struct.jstree({...
```

**Jstree.destroy() is not completly destroying the tree**

Browser appetizingly eats RAM.
Tree data ~= 3-6[MB], Chrome Task Manager [MB]: ~150, ~170 ... 250, 270... 
The garbage collector does not work, even if you wait a while. Somewhere there are links pointing to instances, but I do not do them.

**Comment by vakata** [comment]
Thank you for the report.

I am not aware of any memory leaks, but off the top of my head - make sure you also destroy the actual instance (just to be on the safe side).
Like:
struct.jstree(true) = null;

My guess is any memory leaks should be caused by other code on the page. 
If the above does not help, please provide a demo using jstree only so that I can help further - a jsfiddle perhaps? Also make sure you include the jstree version you are using? 

I will reopen if the above does not solve the issue.

**Comment by Luiz-N** [comment]
I noticed via my sources tab (see below) in chrome dev tools that random web workers kept piling up. I traced it down to this library. Everytime a jstree instance gets destroyed the worker is not being killed along with it. The result is idle workers getting left behind every time a jstree instance is created then destroyed.

![image](https://user-images.githubusercontent.com/3953136/39276119-6bdfdd42-48ad-11e8-89e7-a5922180e285.png)
