### ISSUE TITLE
Weird behaviour of search plugin

### ISSUE THREAD

**Issue by mvachette** [vakata/jstree#1874]
Search plugin sometimes behaves in a way that seems really strange, and at least not predictable.

Here is a fiddle with a sample jsTree with search activated : http://jsfiddle.net/53cvtbv9/1151/

I noticed the following non logical behavior of search : 
- type "p", some results are hilighted, some not, even if my configuration has "show_only_matches" set
- type "pr", same behaviour
- type "pro", ok, now only nodes matching my search are displayed
- type "proo", there is no matching nodes, and then all nodes are displayed. With "only matching nodes" option activated, I expect nothing displayed if nothing match my search (it was the behaviour of previous version of this component)

Is the behaviour described here normal, or is there a bug in search plugin ?

**Comment by vakata** [comment]
This changed back and forth a couple of times - a lot of issues were filed because the tree appeared empty when no nodes match the search term. The predominant opinion was that all nodes should be shown, but with no nodes highlighted as matches. 

You can however use the search event and customize how your UI reacts to that situation - add a message, hide the tree, replace the tree with a message, etc:
https://www.jstree.com/api/#/?q=search.jstree&f=search.jstree

**Comment by mvachette** [comment]
Thanks for your answer. 

Regarding the behaviour when no node is matching, using search event to clear the tree is an acceptable solution for me, il will implement it.

Any idea regarding the behaviour described in the first two bullet poitns on my original message (incorrect hilighting) ?

**Comment by vakata** [comment]
The demo you provided used CSS from 3.0.0-beta and JS from 3.2.1. There is no problem when using CSS and JS from the same version. Here is the updated fiddle (latest 3.3.4):
http://jsfiddle.net/53cvtbv9/1152/
