### ISSUE TITLE
Expand/collapse icons do not work in Chrome on a desktop-size touch screen

### ISSUE THREAD

**Issue by russplaysguitar** [vakata/jstree#1875]
It is not possible to expand or collapse a tree node in Chrome on a desktop-size touch screen monitor. This is caused by Chrome's feature flag: "Touch adjustment", which is on by default. See the Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=625198

As noted in the bug report, the workaround is to make it clear to the browser that the element is clickable: "Ensure the browser knows what elements are intended to be clickable, either with dedicated 'click' event handlers (not relying exclusively on event delegation) or with a :active CSS style." 

This hacky CSS is one way to fix the issue until Chrome fixes the bug: 
```
.jstree-icon.jstree-ocl:active {
    background-color: transparent;
}
```

Another option is to add a empty `onclick` attribute to the `.jstree-icon.jstree-ocl` element. 

Note: For general testing of the Touch Adjustment feature, see: https://rbyers.github.io/touchAdjustment.html

**Comment by vakata** [comment]
Thank you for the report. As you mentioned the workaround involves a CSS rule, which I believe anyone can add to their code until this is fixed, especially since you know best what meaningless rules to add to the :active pseudo class. I do not see the point in working around a chrome bug in the jstree code base. This issue and your solution will get indexed, so for know I believe this is enough. If the Chrome ticket does not get resolved I will consider adding the fix.

**Comment by russplaysguitar** [comment]
That's totally fine, thanks for your quick response!
