### ISSUE TITLE
[NFR] "Checkbox" plugin - ability to prevent node de-selection if parent node is checked.

### ISSUE THREAD

**Issue by temuri416** [vakata/jstree#1880]
Hi Ivan,

I am using cascading 'checkbox' plugin as follows:

```js
checkbox: {
    cascade: 'down',
    three_state: false
},
```

I would like to prevent de-selection of any child node whose parent's checkbox is checked. Disabling children does not suit my needs.

Looking in the code I don't see any way of canceling the event:

https://github.com/vakata/jstree/blob/master/dist/jstree.js#L3229

It would be nice to have a checkbox config that would address this problem.

Cheers!

**Comment by temuri416** [comment]
How about creating "Conditionalunselect" plugin which essentially mirrors what "Conditionalselect" does, only applies to node deselection?

**Comment by temuri416** [comment]
Ping @vakata Any thoughts on this?

**Comment by vakata** [comment]
@temuri416 Sorry for taking so long to respond, yes - I will give the plugin some thought. It sound like a reasonable request. I would probably include it in the additional plugins file, not in the core (as I did with conditionalselect). If it is used frequently (as was the case with conditionalselect) I will include it in the core. 

I will also check if this is a good candidate for extending the conditionalselect plugin itself - it is - I will add it straight to the core.

**Comment by vakata** [comment]
I just added a sample plugin that handles ```deselect_node``` only - you can find it in ```misc.js```:
https://github.com/vakata/jstree/blob/master/src/misc.js#L603

Unfortunately I can not add a solution to the core, as the feature is incomplete and with the current design - it can never be completed: the problem is with ```deselect_all``` - it does not call ```deselect_node``` on each selected node as that would be too slow, so the conditionaldeselect plugin will not capture deselection via ```deselect_all```. The conditionalselect plugin works based on the ```activate_node``` function which is only triggered on user input, so the code can not be used when dealing with node deselection.
Which leads me to my next point - actually the conditionalselect plugin will also capture deselection events - see if it fits in your use case, or use the plugin in ```misc.js```

I will think of a more elegant way of approaching this in v.4.
