### ISSUE TITLE
Shift+Click multiselect behavior

### ISSUE THREAD

**Issue by pm64** [vakata/jstree#1896]
There seems to be a flaw in jstree's Shift + LMB multiselect implementation. The expected behavior of Shift+LMB is for the selected node, the initially-selected node, and all visible nodes (i.e. parent is expanded) between the two to become selected, regardless of their hierarchical level or previous selection status. Jstree will not multi-select via SHIFT+LMB unless the selected node and initially-selected node are on the same hierarchical level, and even in this case, only items between the nodes on the same level are selected, even when deeper nodes are visible. Thunderbird's folder tree is a good reference.

**Comment by vakata** [comment]
I strongly disagree - for me it is counter-intuitive to select a list of nodes regardless of their level. Thunderbird may support that, but I can give the example of popular file managers which don't. Sorry - I will not be changing this. Still - it should be possible to create a custom plugin for this, so that you have this behavior and can still upgrade to newer versions of jstree.
