### ISSUE TITLE
'cascade_to_disabled' not working for deselection of parent group

### ISSUE THREAD

**Issue by KennethSeiero** [vakata/jstree#1919]
I added the following to my code, and down-selection (parent) works like a charm. But deselecting a parent, have no effect on the childnodes. I will have to uncheck them, one by one. 

Is this working as intended?

		'checkbox' : {
			'cascade_to_disabled' : false
		}

**Comment by vakata** [comment]
I am afraid this was never resolved as there is no correct solution. Off the top of my head I can only think of checking all non-disabled children (if this option is set) and if any are checked - deselect all non-disabled children, otherwise select all non-disabled children. With similar checks for hidden nodes. How does this sound?

**Comment by KennethSeiero** [comment]
Thanks for your quick reply, sorry the delay. :)

The solution you proposed, doesn't quite give me the smooth use that i'd like. I've decided to completely ignore importing the nodes, that i don't want the user to select (im using ajax data).

If i change my mind, i might use the above hack to accomplish the same result. :)

I recon adding a option to select which way the cascade_to_disabled should work, would solve the problem. i.e.:

cascade_to_disabled: "down"|"up"|"both"|false

**Comment by vakata** [comment]
I am closing this since you solved your problem and there still is no good option to fix this. Even if I add the option you proposed that will not fix the issue of not being able to deselect a parent.
