### ISSUE TITLE
Can i add custom attributes

### ISSUE THREAD

**Issue by csb-dev** [vakata/jstree#1928]
Hello,
I would like to add custom attributes that i can retrieve when clicking to expand the jstree node.  something like below

leafId = $node.jstree(true).create_node($node, title);
		$leaf = $("#" + leafId);
		leaf_node = $node.jstree(true).get_node(leafId);
		$leaf.attr("stepid", stepid);
this works fine but when i add $leaf.attr("externalid", "xyz");
and then later try to retrieve $leaf.attr("externalid") on the node open event, i get undefined. Is there a way i can achieve this or can i have a custom id value that i can set during the $node.jstree(true).create_node instead of the default one.

**Comment by vakata** [comment]
Yes, instead of a ```title``` string use a valid JSON object:
https://www.jstree.com/api/#/?q=create_node&f=create_node([par,%20node,%20pos,%20callback,%20is_loaded])

The object should follow this format:
https://github.com/vakata/jstree#the-required-json-format

As you can see - you can set any attributes you want - both on the A and LI nodes.
