### ISSUE TITLE
Dragging a browser URL or other text into a jstree

### ISSUE THREAD

**Issue by GreenFootballs** [vakata/jstree#1935]
First, allow me to compliment you on this great library. I'm really impressed with how complete and useful it is.

Second, I'd like to be able to drag a browser's URL (or any other external text element) into a jstree hierarchy, and have it add a new node. I'm pretty experienced with the dnd plugin and its methods, but I've Googled for suggestions and come up blank. Can you suggest a way to do this?

**Comment by vakata** [comment]
I will experiment and let you know - it will probably mean enabling the html5 drag'n'drop feature and then trying to intercept the event and alerting jstree that the dragged element is compatible. If I get it working I will provide a fiddle, otherwise I will add the feature to the core and publish a new version ASAP.

**Comment by GreenFootballs** [comment]
Thanks, looking forward to it!

**Comment by GreenFootballs** [comment]
Just wondering if you've made any progress on this? I have a project in the works that could really use this feature!

**Comment by vakata** [comment]
Sorry for net getting back to you sooner. I did some tests and while dragging seems to work with dnd.html5 enabled the drops do not work (jstree relies on a special key inside the drag data, which is missing when a native element is dragged). 
I will see if the key can be appended later. If it is possible - I will make a demo for you. If not - I will add an option to use whatever key jstree finds in the drag data.

**Comment by GreenFootballs** [comment]
Thanks, Ivan. It sounds like it shouldn't be too difficult to get working. Let me know as soon as you have something, please.

**Comment by GreenFootballs** [comment]
Hi Ivan - any news on this idea yet?

**Comment by vakata** [comment]
Unfortunately - no - I can not reliably detect if the browser's URL is being dragged, or other element. So I do not have a solution yet.

**Comment by GreenFootballs** [comment]
Well, I went ahead and started messing around with this concept myself, and I have something now that's pretty much working. If you have a few minutes, would you mind taking a look at the JSFiddle and let me know if you have any suggestions for improvements?

[https://jsfiddle.net/Green_Footballs/fvnn4c2a/422/](url)

**Comment by vakata** [comment]
That is a great demo! I must have missed you comment! Anyway - you'd have to work with dragover only because start and end are not fired when there is an external object involved. A very rough idea:
https://jsfiddle.net/fvnn4c2a/665/
But you'd have to rework that to make sure that:
1) drag is cancelled once the node is dropped (even outside the browser - maybe some timeouts?)
2) the correct node name is shown in the helper - it is available in the drag transfer object
3) that the default browser drag indication is not shown - I have no idea on how to achieve this

Btw - speaking of native DND - there is an option in the DND plugin that makes jstree use the browser dnd api.
