### ISSUE TITLE
Direct Data JSON Not Update

### ISSUE THREAD

**Issue by ibnuhalimm** [vakata/jstree#1972]
Hi,
I want to create tree view from the result of ajax request.
I get the data but in jstree nothing happened.

There's my code

`function createTree(jsonData) {
        $('.tree_view').jstree({
            core: {
                data: jsonData
            },
            plugins: ['wholerow', 'json_data']
        }).refresh(true);
    }`

`$.ajax({
            async: true,
            type: 'post',
            url: '/url/to/get/data',
            data: {
                team: $('#filter_menu_team').val()
            },
            success: function(data, status) {
                    createTree(data.menus);
            },
            error: function(err) {
                throw err;
            }
        });`

Thanks in advance

**Comment by vakata** [comment]
Check for errors in the console - if there are any - include them here and I will reopen.
If there are no errors - please, provide a demo. I can not help you in any way with the limited amount of information you have provided. Also keep in mind - there is no "json_data" plugin - it was available in v.1 which was year ago. jsTree works with JSON by default now - I am only mentioning this because if yo uare still using v.1 you need to upgrade.

Please provide more info and I will reopen.
