### ISSUE TITLE
Remove nodes but not events

### ISSUE THREAD

**Issue by centerlinemapping** [vakata/jstree#2006]
Is it possible to remove all nodes from the tree, and not destroy all of the events?  I'd like to clear nodes, and readd from ajax request, and removing the nodes breaks the events.  Rebuilding the events does not seem to work either.

**Comment by vakata** [comment]
The only operation which will remove event handlers is ```destroy```, removing nodes or calling ```refresh``` will not destroy bound events. Keep in mind you should use delegated events (binding on the container of the tree) because if you add event handlers to the DOM nodes of nodes themselves (for example LI nodes) those will not work, as jstree will constantly add and remove nodes from the DOM.
