### ISSUE TITLE
The browser is freezing when trying to render more than 1000 root nodes

### ISSUE THREAD

**Issue by saiteja2020** [vakata/jstree#2018]
I am using jsTree in my project to show ratings in a tree view. Great plugin, the Issue I am facing right now is I have a scenario where there are 1000 root nodes although the jsTree is rendering the data properly, the browser(Chrome) is not able to handle the DOM manipulation. The result is it is taking approximately around 2-3 min to display the tree and the page/tab is freezing. I have gone through the API and also the forums and found out that jsTree is not supporting infinite scrolling or pagination yet. In order to solve this Issue I am trying to have a work around like below
If there are more than 50 root nodes then I should show the 50 root nodes along with its children and at the bottom add a link or node or some symbol which says load more, when user clicks on it then the tree renders the next 50 nodes to the bottom and so on. My question here is is it possible to achieve this kind of a workaround (If so how?) and also I have enable drag and drop and editing functionality of the tree, so when ever a user makes any changes I using $("#container").jstree(true).get_json('#', {'flat': true}) to get the changes that are made and saving it to backend, If I am able to make the workaround does this feature effect in any way?
Any help is appreciated. Thank in advance

**Comment by vakata** [comment]
It is not possible to have issues with as little as 1000 nodes (in any browser / machine combination). Here is the default config with 1000 nodes (it loads fine even on my tablet):
http://jsfiddle.net/2kwkh2uL/12232/

How does the above render for you? 
Please share the jstree version you are using (btw, v.1 could have problems with 1000 nodes, but it has not been supported for years), also share your config - provide a little demo so that I can help. Feel free to modify the fiddle above.
I will reopen when more information is available.

**Comment by saiteja2020** [comment]
Hi
Thanks for the quick reply. The version I am using is 3.3.4. It is 1000 root nodes not just 1000 nodes each root node has various child nodes nested upto 4 levels. The total number of nodes are around 7000. I am using flat Json structure i.e it has a parent attribute not children.  Below is the configuration I have used 

    $("#ratingsGrid").on('ready.jstree', function (e, data) {

        data.instance.redraw(true);

    }).jstree({
        plugins: ["table", "dnd", "contextmenu", "checkbox", "ui"],
        checkbox: {
            "keep_selected_style": false,
            three_state: true
        },
        core: {
            "check_callback": function (operation, node, node_parent, node_position, more) {
                if (more && more.dnd) {
                    return  more.pos !== 'i' && node_parent.id === node.parent;
                }
                return true;  
            },
            data : data,

            "expand_selected_onload": false
        },

        dnd: {
            check_while_dragging: true,
            drag_selection: false
        },
        contextmenu: {
            "items": function (node) {
                var defaultItems = $.jstree.defaults.contextmenu.items();
//          defaultItems.create.label = "Ekle";
                delete defaultItems.remove;
                delete defaultItems.create;
                delete defaultItems.ccp;
                return defaultItems;
            }
        },
        // configure tree table
        table: {
            columns: [
                {width: 450, header: "&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; Name"},

                {width: 300, value: "ratingtype", header: "Issue Rating Type"},

                {width: 115, value: "CurrentRatingAction", header: "Rating Action"},

//                {width: 100, value: "CurrentRatingId", header: "CurrentRatingId", headerClass: "customSorting"},

                {width: 100, value: "CurrentRating", header: "Rating"},
                {width: 90, value: "CurrentRW/RO", header: "RW/RO"},

                {width: 100, value: "CurrentRecovery", header: "Recovery"},

                {width: 80, value: "CurrentRE%", header: "RE%"}



//                {width: 80, value: "PriorRating", header: "PriorRating"},
//
//                {width: 80, value: "PriorRW/RO", header: "PriorRW/RO"}

            ],

            resizable: true,

            draggable: true,

            contextmenu: false,

            width: "100%",

            height: "80%"
        }
    });
I am using treetable plugin to show it in a grid view.
I am redrawing the instance on ready of jstree because of alignement problem (https://github.com/adamjimenez/jstree-table/issues/16).
I am trying to reproduce the issue in the jsfiddle but I am not supposed to share the data. I have to create some random data.

Also regarding the work around I asked Is it possible to have a loadMore node at the bottom which render some more nodes so that DOM will not get overloaded
Thanks

**Comment by vakata** [comment]
My guess is that the jstree-table plugin adds a lot of additional DOM nodes and affects the rendering time quite a bit.
As for the node rendering - only visible nodes are rendered in the DOM, keep that in mind (so even if you have thousands of children they will not be rendered if their parent is closed).
You could experiment with disabling core.worker (just in case there is some time spent in building the hierarchy).
As for "load more" - this is currently not possible, and I do not plan on adding it to v.3 because v.4 has infinite scrolling and only viewport visible nodes will be rendered, so it won't be necessary from rendering perspective.

**Comment by saiteja2020** [comment]
The requirement is to show the nodes expanded upto third level and selected on initial load. Thanks for the reply. May I ask when is the version 4 coming out, I am desperately waiting for it since couple of months if infinite scrolling is possible then I think this plugin would be flawless for our application and frankly I have gone through other tree plugins in jquery none of them provide pagination or infinite scrolling so jsTree will be the first one.

**Comment by vakata** [comment]
Unfortunately I do not have and ETA for v.4. jsTree is a project I maintain in my free time and I haven't had much of that in recent months. It definitely won't be ready in the upcoming weeks or even months. I will however do my best to publish a beta-branch here, so that other devs (like you) can help with the development if they can.

**Comment by saiteja2020** [comment]
Thanks for the frank reply. I request you to release a beta branch as soon as possible. Thanks again for the plugin
