### ISSUE TITLE
select_node without loading it

### ISSUE THREAD

**Issue by MrLeninstalock** [vakata/jstree#2021]
Hi guys,

Gg for Jstree, really nice work !

One question remains for me. Do I have to load a node before opening-it ?

I have like 10 000 nodes, all roots nodes. Each root node has +50 total childrens.
And I have links, when I click on one link, it is supposed to open the node corresponding to the link. BUT this nodes can be at depth-3.
So actually I'm doing a `load_all` and then and then a `select-node`. I've developped this using test files of 30 nodes, it was ok. Now with my 10 000 roots, it's really slow.

Is there no way to recursively go to the one node I'm looking for ? I've tried the `_open_to` methods but doesn't work ...

I would like to avoid the `load_all` tht causes serious performances issues ...

Baptiste

**Comment by vakata** [comment]
In order for jstree to select a node, it has to know that the node exists. If the lower level nodes are not loaded there is no way for jstree to find that node.

Implement your own custom logic to only load the needed parents (similar to what the search plugin does).  
When the user clicks the link you mentioned - make an AJAX call to the server and return only the parents of the node you want revealed and then call ```load_node``` with that array as an argument. Once the operation completes (you can use the second argument - the callback) it will be possible to work with that node.  
For example, if you have a structure like this:
```
root_1
  child_1.1
     child_1.1.1
```
And the user clicks a link to select child_1.1.1 but you only have the root level loaded do this:
```js
$.get('/parents?id=child_1.1.1').done(function (data) {
   // data contains the parents: ["root_1", "child_1.1"]
   $('#tree').jstree(true).load_node(data, function () {
      $('#tree').jstree(true).select_node("child_1.1.1");
   })
})
```

Unfortunately that is all I can help with. jsTree simply needs to have the node loaded in order to work with it. Let me know if I can help further.

Best regards,
