### ISSUE TITLE
wholerow plugin causes scrollbar while expand/collapse nodes

### ISSUE THREAD

**Issue by mupchrch** [vakata/jstree#2028]
Issue can be seen on https://www.jstree.com/docs/config/

Notice the tree using the wholerow plugin (the bottom tree), has a scrollbar visible as it is resizing. The tree without the plugin (the top tree) does not have the scrollbar.
![demo](https://user-images.githubusercontent.com/5797698/41599802-37d49464-73a2-11e8-89a0-369a43b6fddb.gif)

**Comment by mikila85** [comment]
@mupchrch did you find any workaround for this?

**Comment by mupchrch** [comment]
@mikila85 Unfortunately, no. Spent some time trying to figure out a CSS solution, but didn't get anything working.

**Comment by vakata** [comment]
This can be fixed by setting ```overflow:visible``` or ```overflow:hidden``` to the container (depending on your use case). ```overflow:auto``` will cause a scrollbar to appear even if it is not needed but only if the container height is affected, which really should not be the case - if the height is fluid there is no point in setting overflow to auto. I will investigate this further, but I believe the above is a valid solution - if you disagree - let me know and I will reopen.
