### ISSUE TITLE
Ultra minor cosmetical 

### ISSUE THREAD

**Issue by sebkob** [vakata/jstree#2044]
![bold line](https://user-images.githubusercontent.com/39202827/42405243-367ec720-8193-11e8-99cb-35a2e25b80a3.PNG)

The vertical dotted line that is not connected to the last leaf is more bold than the other dotted lines.

**Comment by vakata** [comment]
Unfortunately there is nothing I can do about this - it is usually related to browser zoom. jstree v.4 will use SVG instead of PNG and this probably will not be an issue, but there is nothing I can do for v.3 - it is quirk that shows up in some browsers (usually when zoom is not at 100%). Sorry, I am closing this as won't fix (and I believe it will not be an issue in v.4).

**Comment by sebkob** [comment]
When do you anticipate to release v.4?
