### ISSUE TITLE
display the minimized view icon theme all the time

### ISSUE THREAD

**Issue by xbonner13** [vakata/jstree#2048]
I want to be able to display the theme when your looking at the jstree view in a smaller window all the time like below.  How would I go about doing that?
![capture](https://user-images.githubusercontent.com/25233945/42851299-fb73d5de-89f9-11e8-931e-1669ea7f5031.PNG)

**Comment by vakata** [comment]
This is not possible out of the box, but you could add your own theme based on the default jstree theme. To do this you can either:
a) copy the theme (copy and rename the themes/default folder), rename it (the folder) with your own name, replace ```default``` in the css file with your name and modify the ```media``` query so that it matches all the time. 
b) or if you need more customization - create your own theme by modifying the .less files - that way you won't have to search and replace in the file, etc. 

In both cases - remember to include your new CSS file in your page and configure the tree to use the new theme:
https://www.jstree.com/api/#/?q=theme&f=$.jstree.defaults.core.themes.name
