### ISSUE TITLE
redraw(or redraw_node) is not working

### ISSUE THREAD

**Issue by wonsuc** [vakata/jstree#2059]
I'm trying to update created node with a retrieved data from ajax call.

I used [redraw](https://www.jstree.com/api/#/?f=redraw([full])) method and it doesn't seem to work. `redraw_node` is not working too.

It only works if I call `refresh` but it refreshes whole nodes with networking which creates lagging.

I found [related stackoverflow qusetion](https://stackoverflow.com/q/26532967/4729203) and it seems many people also having same issue.

Is there any workaround with it? Thanks.

**Comment by vakata** [comment]
Both functions work fine - otherwise you will get a blank tree. 

Calling ```refresh``` refreshes the tree (or a node) by fetching data from your specified data source - it is normal to have network activity since this is your data source.

As for updating a node with some data from an AJAX call - how exactly are you doing this? The only way I can think of is modifying jstree's internal datastore and then calling ```redraw``` **on the parent node**. But I would only do that if you know exactly what you are doing as this is internal data and it is not supposed to be modified outside of jstree.

If I misunderstood and the above does not point you in the right direction - please provide more info and I will reopen.

Best regards,
Ivan
