### ISSUE TITLE
Dom hanged for couple of minute while selecting more  than 800 records in jstree during initialization

### ISSUE THREAD

**Issue by ankurtg00009** [vakata/jstree#2074]
Dom hanged for couple of minute while selecting more than 800 records in jstree during initialization

**Comment by vakata** [comment]
How did you select those nodes, and how large is the data set? 
Rendering a flat set of a few thousand nodes usually takes a few seconds.
If the problem is with selection only - make sure you are not selecting the nodes one by one - pass an array to ```select_node``` or ideally - send the state with the data.

Please provide more information so that I can help.

**Comment by vakata** [comment]
I will reopen when more information is available.
