### ISSUE TITLE
JS Tree check and uncheck based on search

### ISSUE THREAD

**Issue by kirandas82** [vakata/jstree#2215]
Initially all my nodes will be open and checked, on search I just wanted to show the searched nodes and onlyn those should get selected; is that possible?

**Comment by vakata** [comment]
It all depends on your config (some combinations are not logically possible - for example if **three_state is on**, and you have a parent with two children - one checked, and one not - it will not be possible for the parent to be checked - that is by design). Aside from that - just browse the API - you have all the events and methods available, like the search.jstree event and the check_node method (which accepts an array as well).
