### ISSUE TITLE
Massload with open_all in JSTree with Lazy Loading

### ISSUE THREAD

**Issue by allipierre** [vakata/jstree#2260]
Hallo,

is there a way to open all nodes using  massload plugin?

$(".jstree").jstree("open_all");

Now when i use open_all , it make each request for each id to the Server and it is slow.

i use now jstree 3.3.8 with lazy loading

Thanks for Support

**Comment by vakata** [comment]
There is no way to do that. Massload only helps when the IDs that need to be loaded are known - for example when using the state plugin, or the search plugin (with server side searches). You could call ```load_node``` (instead of ```open_all```) with an array of nodes (provided you know them) and massload will kick in. The other option is to return all descendants from the server when ```open_all``` is invoked, but that would involve setting some kind of flag. I'd go with ```load_node``` and pass an array.
