### ISSUE TITLE
jsTree: with lazy loading the plugin “dnd” is not working

### ISSUE THREAD

**Issue by ckleis** [vakata/jstree#2324]
Hi vakata,
I'm using jsTree 3.3.8. I have a lot of nodes to display in the tree, so I load only the first subtree initially and for the other subtrees I'm using lazy loading with children: true;  This works fine!

But if I try to use drag and drop within the lazy-loaded subtree or from the first (initially loaded) subtree to an other (lazy loaded) tree, the red X icon is shown and the browser (Chrome and Firefox) freezes. No furher action is possible.

Here my code, if it helps:
```
$("#navigationTreeContainer")
        .jstree({
            "core":{
                "multiple": true,
                "data": {
                    "url": "{{ treeNodesAjaxUrl | raw }}",
                    "data": function(node) {
                        return {
                            'id' : node.id
                        };
                    }
                },
                "check_callback" : true
            },
            "plugins":[ "state", "wholerow", "changed", "dnd", "contextmenu"],
            "contextmenu": {
                "items": navigationRightClickMenu
            }
        })
        .on("move_node.jstree", function (e, data) {
            moveNode(data.node.id, data.parent, data.position);
        });
```
The problem still exists when I remove my event moveNode().

In issue https://github.com/vakata/jstree/issues/1553 the same problem is already descripted.

I would be very grateful for a tip or your help.
Carmen

**Comment by vakata** [comment]
Here is a demo with ajax loading and DND: http://jsfiddle.net/nrfoqjwt/ - seems to work fine.
My guess is that your IDs are duplicated or that something is wrong with your data, but I can not say for sure without a demo.
I am sure this is specific to your data, but please do provide a demo and I will help.

**Comment by seanrockster** [comment]
@vakata 

Hello I'm having the same issue. Pulling my hair out trying to figure out what the problem is. The examples all work however when i load my data dnd doesn't work. I understand its probably my data but for the life of me i cannot figure it out. I've looked for duplicate IDs, no duplicates so I'm struggling to see what the problem. 

I would be great if you suggest something? I'm only using dummy data i'm happy to share and my tree config.

**Comment by vakata** [comment]
@seanrockster By all means - please share a demo so that I can have a look.

**Comment by seanrockster** [comment]
Hi @vakata 

Thanks for your reply. I found my issue which was in the configuration, the plugin element was inside of the core so that is why it wasn't working.

Although its working I do not get the little arrows to indicate where the drop will happen. I'm using a bs4 template. I did a quick search but didn't find anything related to that issue.

Again, thanks.

**Comment by vakata** [comment]
Sorry - no idea why they are not showing up - maybe a z-index related issue specific to your layout? If you share a demo I will have a look.

**Comment by monopol40** [comment]
My dnd works only with single quotes. this works: "plugins": ['dnd'],
but not this "plugins": ["dnd"],
