### ISSUE TITLE
prevent_open option doesnt seem to be working for select_node function

### ISSUE THREAD

**Issue by senthilvelk** [vakata/jstree#2325]
I have a big dataset. It contains parents and child nodes. On loading the jstree, I would need to select the child nodes dynamically based on the saved state data. When the nodes are selected, the parent nodes are opening up. I tried to use the option prevent_open=true in the select_node function. Even then, it is of no help. Any suggestions?

**Comment by vakata** [comment]
The state object also contains which nodes should be opened. You can however "clean" the state object before applying it (so that you can remove the "core.opened" property) or you could simple call close_all once everything is done (if that fits your use case).
https://www.jstree.com/api/#/?q=state.filter&f=$.jstree.defaults.state.filter

**Comment by senthilvelk** [comment]
Thank you for your reply.
