### ISSUE TITLE
Simple loading of trees from json and refreshing.

### ISSUE THREAD

**Issue by jermp** [vakata/jstree#2368]
Hi,
I've set up a minimal example where I get some json
data and initialize a jstree with it.
The data is coming from a file which is selected using
an input field, so I would like to update the tree whenever
I specify the name of a new file. My code looks as follows.

    var filename = document.getElementById("filename").value;
    $.getJSON(filename, function(json) {

        console.log(json);

        $("#tree")
        .jstree({
            "core" : {
                "themes" : {
                    "stripes" : false,
                    "dots" : true
                },
                "check_callback" : true,
                "data" : json
            },
            "plugins" : [ ]
        });

        var tree = $('#tree').jstree(true);
        tree.refresh();
    });

The problem is that it works only the first time, then it seems to not refresh.
The console.log shows that the json data is there correctly.
I just do not know how to refresh the tree with the new data.

I have searched the web and found that many people experienced the same issue
but I was not able to find a working solution.

Please help, thanks.
-Giulio

**Comment by vakata** [comment]
This is not jstree related, but anyway:
You have initialized the tree with some static JSON, so when you refresh it - it will still be the same. If you want to use a new JSON - either recreate the whole tree with the new JSON (instead of invoking refresh), or set core.data to a function, which in turn checks the input value, loads the file and returns the new JSON.

**Comment by jermp** [comment]
Thanks for the reply, but how do I recreate the tree with the new json?
Can you provide an example?
