### ISSUE TITLE
Avoid selecting all children but propagate to parent node

### ISSUE THREAD

**Issue by jermp** [vakata/jstree#2372]
Hi,
when using the plugin `checkbox`,
is it possible to avoid selecting all children nodes but selecting the parent nodes (up to the root)?

I have read the docs here https://www.jstree.com/api/#/?q=cascade,
and played with cascade options: it seems that setting `"three_state" : false`
and `"cascade" : "up"` should do the trick, but unfortunately it does not.

Do you have any clue?
Many thanks in advance.
-Giulio

**Comment by vakata** [comment]
The options you have specified will work of the selected node is an only child, otherwise the selection will propagate up ONLY if all the other siblings are checked (then the parent will be checked as well).
There is no option for what you need - do it yourself - disable three_state and cascade, and on check - get the node's ancestors (there are methods for that) and check them.

**Comment by jermp** [comment]
Why this does not work?

    tree.on('check_node.jstree', function(e, data) {
        console.log(data.node.text);
    });

I am only able to do this instead:

    tree.on('changed.jstree', function (e, data) {
    });
