### ISSUE TITLE
Has there been any progress or idea when it will be relased?

### ISSUE THREAD

**Issue by jplevene** [vakata/jstree#2738]
I am willing to start donating again, however last time I did, nothing happened with development.  We don't want to move to another tree, however due to the lack of virtual rendering (only rendering to the DOM what is displayed), we are having to look at alternatives like pqGrid's treeview.

We really want to stick with jsTree as we feel it looks far better, however we will eventually be forced to abandon it.

**Comment by lofcz** [comment]
Same, I've donated to this project for almost a year, and not much has happened. I'm willing to donate again once there is some progress toward v4.

**Comment by vakata** [comment]
@jplevene @lofcz let me apologize again - I am very sorry, I could not achieve more and I am sorry you are disappointed. There was at least some progress made while there were active donations, but unfortunately - not as much as I had hoped. 

As much as I love to work more on jstree, as it is my baby (my first and most publicly adopted project), I am finding it difficult to find the time to develop it because of work, personal life and health issues. 

I really hoped jstree will reach at least 100$ a month of donations, just as an indication that the project is still valued and needed by a wider community. Unfortunately it is yet to reach this goal. I am not talking about "buying dev hours", just as a symbol (I believe we all know how much 100$ will buy in terms of dev work).

Anyway - I am going off topic. I can not give a hard date on when v4 will be out. It is sad to see you guys migrating to other products - especially with jstree being maintained and developed for almost two decades. Unfortunately my priorities have shifted and my opensource work is taking a hit. I hope to find more time to work on jstree, or to integrate it as part of larger sponsorship deals (as I have done with some of my other opensource projects).

Once again - I apologize.
