### ISSUE TITLE
Populating a tree using HTML removes custom HTML

### ISSUE THREAD

**Issue by h0lg** [vakata/jstree#427]
I was just forced to switch from version 1 to 3 because the API reference for v1 is gone :(
I am currently trying to make jsTree render a tree from HTML.
While version 1 allowed for custom HTML content in nodes, version 3 seems to remove everything but the anchor holding the node text.

This is the HTML of a sample node before I let loose jsTree v3 on it:

``` html
<li data-node-id="976" id="node976">
    <i class="customNodeIcon"></i>
    <a title="foo" href="#">the node text</a>
    <span class="tag">a tag</span>
    <i title="go some place else" class="nodeLinkIcon" data-node-url="http://some.external.link/976"></i>
    <span title="something is wrong with this node" class="warning">
        <i class="customWarningIcon"></i>
        <span>Something is wrong with this node...</span>
        <span class="warningTooltip" style="display:none">
            <span>
                <i class="customWarningDetailIcon"></i>This explains what's wrong
            </span>
        </span>
    </span>
</li>
```

And those are the poor remains of that same node after the tree is rendered:

``` html
<li role="treeitem" id="node976" class="jstree-node  jstree-leaf">
    <i class="jstree-icon jstree-ocl"></i>
    <a class="jstree-anchor" href="#" title="foo">
        <i class="jstree-icon jstree-themeicon"></i>
        the node text
    </a>
</li>
```

As you can see, there's quite a bit of a difference here...

I would have expected the tree to look weird after I upgraded to a new major version.
I was prepared to rewrite the event handlers and adjust the CSS.
However, I did _not_ expect jsTree to just rudely remove everything that doesn't fit.

I read the new API reference, I skimmed through the code but I couldn't find the option or hook or event handler that lets me overwrite the rendering or use the existing HTML without changing it or whatnot :(
Am I missing something? How am I supposed to use the v3 API to keep my HTML?

**Comment by gicalle** [comment]
Hello Ivan @vakata ,
The id and classes / attributes from the ul tag are removed.
For the li tag the classes and id are kept.
Is it possible to make a change to your code so that the info included in the original ul tag is copied to the tree layout?

**Comment by vakata** [comment]
I would rather not do that - I am focused on v.4 and I will not be adding features in v.3. As a workaround - add your classes to the DOM node once the ```ready.jstree``` event fires - the UL is created once and not changed, so it is safe to add your classes as soon as the DOM node is in place.

**Comment by shruthikakwe** [comment]
Hi Ivan, @vakata 

Need your help to solve my problem: 
I am using JStree 1.0 and now trying to migrate data from xml to html(I have around 8000 nodes). But JStree excludes all ul elements of html except the outer <ul> list. Because of which my data is displayed as one long single list instead of tree. 
Example 
html data populated from data base using C#:
<ul>
   <li id ='608' parent_id='600'><a href="#"> First Name1 </a></li>
       <ul>
              <li id ='609' parent_id='600'> <a href="#">Last Name2</a></li>
       </ul>
</ul>
Structure after tree is populated:
<ul>
 <li id="608" parent_id="600" class="jstree-leaf"><ins class="jstree-icon">&nbsp;</ins><a href="#"><ins class="jstree-icon">&nbsp;</ins>First Name1l</a></li>
<li id="609" parent_id="600" class="jstree-leaf"><ins class="jstree-icon">&nbsp;</ins><a href="#"><ins class="jstree-icon">&nbsp;</ins>Last Name2</a></li>
</ul>

C# code:
<asp:Content ID="Content3" ContentPlaceHolderID="leftContent" runat="server">
	<div id="html2">
		<asp:Literal ID="html1" runat="server">
		</asp:Literal>
	</div>
        <script type="text/javascript">
	      $(function () {
		   $("#html2").jstree({ 
		   "plugins" : [ "themes", "html_data" ]
	            });
               });
          </script>
</asp:Content>

I am populating rightly ordered <ul> and<li> elements But it's changed by jstree. How can I populate the tree correctly?

**Comment by tacman** [comment]
Is there a way to style the text in the li?  That is, I want to add a superscript badge, change the color in certain cases, etc.  

I tried adding html to the text, but it renders it as escaped html (that is, rendering <b>6</b>, instead of bolding it).

I see there used to be an html_data plugin, not sure if that's relevant.  I was hoping there would be some sort of onRender event for the left.

Great plugin, I'm using the AJAX loading it's perfect for what I'm trying to do.  Thanks.
