### ISSUE TITLE
Checkbox plugin selects disabled children

### ISSUE THREAD

**Issue by DJCrossman** [vakata/jstree#747]
Selecting a parent checkbox in a jstree will select all children checkboxes regardless of whether they're disabled. 
![image](https://cloud.githubusercontent.com/assets/3226939/3458416/48487430-0201-11e4-8a8d-61e0396e6785.png)
![image](https://cloud.githubusercontent.com/assets/3226939/3458420/50a8ff96-0201-11e4-9064-ec12dcf2ae23.png)

**Comment by briansoule** [comment]
@vakata Where is the warning?

**Comment by vakata** [comment]
Last sentence in the checkbox plugin description: http://www.jstree.com/plugins/
Why?

**Comment by briansoule** [comment]
Was just futzing with the checkbox issue where the parent will select disabled children. Perhaps we could write something about this in the readme?

**Comment by vakata** [comment]
Just added a note in the readme file too.

**Comment by briansoule** [comment]
Thanks, is there a configuration where a parent will check all the non-disabled children, and leave the disabled ones unchecked?

**Comment by vakata** [comment]
No, there isn't, sorry.

Best regards,
Ivan

**Comment by zolakt** [comment]
Could you make it an option if not default behavior?
I tried changing it myself, but ended with new bugs.
No offense, but this doesn't make a lot of sense. If you disable something you expect it can not be changed in any way.
As for, "correct" behavior I completely agree with landonr suggestion

**Comment by vakata** [comment]
Sorry, but cascading the disabled state makes no sense to me in some cases. I regularly use jstree with disabled root nodes (so that they are not selectable by user input). So if I go this route - that would mean adding this as an option too. 

Quite frankly - disabled nodes with cascading is an impossible problem - we can argue a lot about what is correct and in one use case you will be right, in the other - I. 

In the end I decided to leave the disabled option as described - not selectable by direct user input. Cascading will select disabled nodes and the developer can select disabled nodes too using the API.

Adding a new option will mean a lot of rewrites and a huge performance drop in the checkbox plugin - imagine the cascading hell that would ensue, which in turn need new config options - how about a disabled node, which I choose not to enable if its parent is checked - so far so good - what about the children of that disabled node - new config options?

Most of the time any problem with disabled nodes and cascade can be fixed with a few lines of "own" code, as the fix is for a concrete piece of code, where you know the desired effect. A general solution is nearly impossible, at least for me. If someone wants to contribute an alternative checkbox plugin, I will be more than happy to merge it in the core if it works properly.

Best regards,
Ivan

**Comment by banejo** [comment]
Was there ever any progress on this, or is this still broken?  I find the plugin unusable with this bug.

You claim "Most of the time any problem with disabled nodes and cascade can be fixed with a few lines of "own" code", do you have an example of what you mean by this?

Many thanks.

**Comment by banejo** [comment]
Above you said "If selection cascades down it is fairly easy to skip disabled children.".  Can you direct me to where I would add this check?  This is the functionality change that is the most important to me.

Many thanks.

**Comment by warrenAR** [comment]
I have a solution! It works for my 1-deep tree. 

I've added the following:

```
$("#selectionTree").on("select_node.jstree", function(evt, data) {
    var currentNode = data.node;

    //rember opened state for later
    var openedState = currentNode['state']['opened'];

    //need to open node for accruate selection       
    $('#selectionTree').jstree('open_node', currentNode);

		//get child nodes
    var children = $(this).jstree("get_children_dom", currentNode);

		//this allows selections parent nodes to deselect children (without it, there is no three-state)
    if ($("#" + currentNode['a_attr']['id'] + " > i").hasClass("jstree-undetermined")) {
      for (var i = 0; i < children.length; i++) {
        $(children[i]).jstree("deselect_node", children[i]);
      }
    }

		//loop through child nodes and select all except disabled nodes
    for (var i = 0; i < children.length; i++) {
      var obj = $.parseJSON($(children[i]).attr('data-jstree'));
      if (obj['disabled'] == true) {
        $(children[i]).jstree("deselect_node", children[i]);
      }
    }

		//return parent to closed state if was already
    if (openedState == false) {
      $(this).jstree('close_node', currentNode);
    }

});
```

And the working fiddle: https://jsfiddle.net/Lf55r7qt/6/

**Comment by vakata** [comment]
It is already in the plugin itself:
https://www.jstree.com/api/#/?q=checkbox.cascade_to

**Comment by warrenAR** [comment]
Thank you - were they in V3.0.8?

Also, in this fiddle, I use the cascade_to_disabled, but I cannot deselect a parent node in the undermined state - is this correct? https://jsfiddle.net/9n4vpo35/

**Comment by KennethSeiero** [comment]
Works like a charm, thanks for adding this!

		'checkbox' : {
			'cascade_to_disabled' : false
		}
