### ISSUE TITLE
on loading jstree, if parent node is selected:true, child also becomes true and parent overrides child selected property

### ISSUE THREAD

**Issue by MePanMsn** [vakata/jstree#809]
I am feeding this data to jstree,
               'data': [
                    { "id": "GrandPa", "parent": "#", "text": "Grand Father" },
                    { "id": "Dad", "parent": "GrandPa", "text": "Dad", "state": { selected : true } },
                    { "id": "Son", "parent": "Dad", "text": "Son", "state": { selected: false } },
                    { "id": "Daughter", "parent": "Dad", "text": "Daughter", "state": { selected: true } },
                ]

The node "Son" appears checked on load. However it should be unchecked because i set the property selected:false
It appears that if parent node is selected:true, child nodes are forced to be true as well irrespective of their own selected property.

**Comment by manu102** [comment]
I am trying to implement a jstree using data from mysql table 'Sections ' with following attributes : Section ID, section no, taid, year and semester. the problem is that I am getting the year and semester repeated.Can you please help me. I have my code attached.


<?php
$database = new Database1();
		
	$dbconn = $database->getConnect();

	$sql = "SELECT * FROM Sections WHERE taId=" . $_SESSION['user_id'];
		$id=$_SESSION['user_id'];
	$result=$dbconn->query($sql);	
	

?>
<div class="row center-block">

    <div class="panel panel-default">
  <div class="panel-heading panel-heading-custom"><?php echo $lang['FILE_BROWSER'];?></div>
  <div class="panel-body" id="data">
   <?php while($row=$result->fetch_assoc()) { ?>
	<ul>
      <li><?php echo $_SESSION['name_e']; ?></li>
        <li><?php  echo $row['year']; ?>
          <ul>
             <li><?php  echo $row['sectionNo']; ?></li>
           </ul>
             
       </li>
       <li>three</li>    
      
     </ul>	
 
</div><?php  }?>  

</div> 
</div>
