### ISSUE TITLE
select_node selects multiple nodes event when core.multiple is false

### ISSUE THREAD

**Issue by MajedDH** [vakata/jstree#893]

**Comment by hammond13** [comment]
This is good to know, though it doesn't solve the problem for me since the activate_node function doesn't accept the suppress_event parameter. I'm wondering in what circumstances you would set core.multiple to false but want to select more than one using the select_node function.  I expected it to work the same way a select box works without the multiple parameter. I think that would be the most intuitive behavior.

**Comment by vakata** [comment]
I will consider this for v.4 (as it is a breaking change).

Best regards,
Ivan
