### ISSUE TITLE
Ability to select multiple nodes using SHIFT+LMB

### ISSUE THREAD

**Issue by cowwoc** [vakata/jstree#9]
jsTree supports selecting multiple nodes using CTRL+LMB. We should also be able to select a range of nodes by selecting the first, then SHIFT+LMB to select all nodes between the first and second node. See http://www.immense.net/adding-shift-multiselect-jstree-jquery-plugin/ for a related discussion.

**Comment by pm64** [comment]
There seems to be a flaw in this implementation. The expected behavior of Shift+LMB is for the selected node, the initially-selected node, and all visible nodes (i.e. parent is expanded) between them to become selected, regardless of their hierarchical level or previous selection status. Jstree will not multi-select via SHIFT+LMB unless the selected node and initially-selected node are on the same hierarchical level, and even in this case, only items between the nodes on the same level are selected, even when deeper nodes are visible. Thunderbird's folder tree is a good reference.

**Comment by sagittaracc** [comment]
> jsTree has supported range selection for quite some time now. Even the not yet ready 1.0 branch has it. Maybe you are referring to the ability to select a range that does not consist only of siblings? This is easily achievable, but I am not sure if it is very usable?
> 
> Cheers, Ivan

Could you please show how i can select a range that does not consist only of siblings?
