### ISSUE TITLE
Read-only jstree

### ISSUE THREAD

**Issue by milkovsky** [vakata/jstree#933]
I want to render tree of organizations. I don't want to use it for editing. It is a read-only data.
How can I disable "selection" function for the jstree?
I can disable all the nodes, but then the icons are grey.

**Comment by milkovsky** [comment]
conditionalselect didn't help me.
I'm using:
```javascript
       var options = {
          'core' : {
            'data' : value.hierarchy,
            'themes' : {
              'variant' : 'large'
            }
          },
          'plugins' : ['conditionalselect'],
          "conditionalselect" : function (node) {
            return false;
          }
        };
        var $container = $('#' + index);
        $container.jstree(options);
```
But the items in the tree are still selectable

**Comment by vakata** [comment]
Did you add the plugin to the page? It is not in the `jstree.js` file, you need to copy it manually and add the script file yourself.

**Comment by slominskir** [comment]
Am I understanding correctly that you must install a third party plugin in order to disable the selection feature?   It would make more sense to have to install plugins to add features, but not to remove them!  Why not have a core configuration parameter similar to the existing selection configuration of "multiple", but call it "selectable" with true/false values to control whether selection is enabled.

**Comment by vakata** [comment]
It is not a third party plugin - it is developed by me and is in this very repo. The reason for a separate plugin is that 99% of the use cases do not need to disable selection, so out of the box jstree simply tries to satisfy the 99%. v.1 was different and was like you proposed - a ton of settings, which meant almost everybody had to read too much to configure their tree and in the end - did not even succeed.

Best regards,
Ivan

**Comment by slominskir** [comment]
I used version 1 and thought it was pretty good.   I don't use the selection feature, but I guess I'm in the minority.  It is a nice feature and maybe I'll use it in the future, but for now I allow users to pop up dialog boxes by clicking on nodes so selection doesn't really fit in this use-case.

I'm upgrading to version 3 to get the state saving plugin, but it turns out the upgrade is tricky.   A few issues so far:

1. The API has changed dramatically (for example types configuration doesn't have "image" property;  initially open is handled differently, and many more differences).
 
2. Using custom html to generate nodes is not as useful now since the HTML you create is being erased and replaced by the fixed structure anyways (I was adding an extra icon for two icons side-by-side per node.  I now do this stuff with jQuery and CSS "content and ::before" trickery)

3. I had to copy the "default" theme and rename it "classic" and then splice pieces (boxes with + and -) out of the old d.png file into the new 32px.png file.

4. Copy and paste conditionalselect plugin and invoke it to disable selection

This is a nice tree widget so the one-time cost of upgrading should be worth it.

**Comment by vakata** [comment]
Hi again,

Sorry for your troubles but this upgrade was very necessary. I was able to clean up a lot of stuff, and since the API is different not only did I increment the major version counter, I even skipped v.2 (which was abandoned and was never released). 

The image and position options were removed in favor of classes, which provide more flexibility anyway.

As for custom HTML - that too was necessary, I am afraid. Supporting all kinds of funky markup was exhausting. So now if you want extra markup you can create a plugin (I provided a few icon-adding plugins in src/misc.js).

I also had to ditch the various themes - the default theme with its 3 sizes and 2 color schemes is enough - as you saw it is not very hard to create a custom theme.

I hope the upgrade was worth it for you. I can assure you v.3 is a lot faster and more stable than v.1 ever was. I hope you like the new jstree and continue to use it.

Best regards,
Ivan
