### ISSUE TITLE
using opened: false and selected: true

### ISSUE THREAD

**Issue by fjallraven** [vakata/jstree#945]
Apologies if this has been covered before, I searched through issues but couldn't find it.

I've tried setting "initially closed" leaf bellow to opened: false but if set to selected: true it will be expanded by default.

```javascript
    $(function () {
        $('#jstree1').jstree({'plugins':["wholerow","checkbox"], 'core' : {
            'data' : [
                {
                    "text" : "Same but with checkboxes",
                    "children" : [
                        { "text" : "initially closed", "state" : { "opened" : false, "selected": true }, "children" : [ "Another node" ] },
                        { "text" : "custom icon class", "icon" : "glyphicon glyphicon-leaf" }
                    ]
                },
                "And wholerow selection"
            ]
        }});
    });
```

Any ideas?

Thank you!

**Comment by vakata** [comment]
Set `core.expand_selected_onload` to `false` in this config. 
To explain in detail - since you are using checkboxes, the nodes that are children of "initially closed" are considered selected (because the parent is and the parent's state is cascaded down). By default all selected nodes are shown (their parents are opened), because that would make more sense to the end user (especially if checkboxes are not used). But you can disable this behavior with the above mentioned setting in the config.
http://www.jstree.com/api/#/?q=expand&f=$.jstree.defaults.core.expand_selected_onload

Best regards,
Ivan

**Comment by fjallraven** [comment]
Thank you Ivan!

Much appreciated
