### ISSUE TITLE
bug displaying path?

### ISSUE THREAD

**Issue by ryzott** [vakata/jstree#959]
Displaying the path from the HTML tree contains space, but in the JSON tree there is no space.
Here is the example:
http://jsfiddle.net/2kwkh2uL/797/

**Comment by vakata** [comment]
This is because when using HTML jstree will automatically get all text contents of the LI node and use it as the text for the node, in your case you have `...<li>Root[NEW_LINE][TAB]<ul>...`
So the node text becomes: `Root[NEW_LINE][TAB]` 

There is no safe way for jstree to exclude white space, as the white space may really be a part of the node, so you should either use:
`<li>Root<ul>...`
or
`<li><a href="#">Root<a>...`

Best regards,
Ivan
