### ISSUE TITLE
Having 'children' as a property value is parsed as a property name of 'children'

### ISSUE THREAD

**Issue by dleffler** [vakata/jstree#963]
In v3.0.9 (not sure about earlier versions), when using the Alternative JSON format and you have a property VALUE of 'children' is appears that jstree determines the json data is using the standard JSON format with a property name of 'children'.  The result is an Uncaught TypeError: Cannot read property 'children' of undefined.  Furthermore, this only seems to occur when you have a 'state' property defined.

**Comment by vakata** [comment]
Thanks for reporting, but can you provide a demo for this, because I can not reproduce the issue:
http://jsfiddle.net/DGAF4/249/
Could you modify this simple demo so that I can pinpoint and fix the issue.

**Comment by dleffler** [comment]
Demo modified

**Comment by vakata** [comment]
How about the link? :)

**Comment by dleffler** [comment]
http://jsfiddle.net/dleffler/uLeLb1cx/

**Comment by vakata** [comment]
The error has nothing to do with "children" being used as a value. The problem is with the structure - there is a node, whose parent ID is not in the structure, which makes the whole structure invalid and jstree can not parse it (for example having a node whose parent is 3, but there is no node with the ID of 3 in the data).
 
Here is a more simplified example:
http://jsfiddle.net/uLeLb1cx/1/

Best regards,
Ivan
