### ISSUE TITLE
Drop only possible on item' text - not the whole row

### ISSUE THREAD

**Issue by marcuspflanz** [vakata/jstree#965]
Hi,

we are using jstree and several of its plugins to display items and groups of items as folders.
We have added a policy to ensure:
- items can't be dropped on other items
- items can be dropped on folders
- items can be dropped between items (as they would've been dropped on the folder)

When dropping an item on another one it should be placed in between this item and its next neighbour. This works perfectly fine when targeting the item' text.
Issue is: This does not work when targeting the item' row outside of the item' text (see attached screenshots).

![drop available](https://cloud.githubusercontent.com/assets/7021202/5834790/75174036-a161-11e4-92b9-6c7dc97d1ceb.jpg)
![drop unavailable](https://cloud.githubusercontent.com/assets/7021202/5834793/78c46092-a161-11e4-83c6-7633b178d991.jpg)

Side note: Row itself is highlighted by using 'wholerow' option correctly - just the logic does not work as intended.

Can anyone confirm this as a bug or any fix/workaround to solve the issue?
Please tell me if you do require additional information.

Best regards,
Marcus

**Comment by vakata** [comment]
To be honest, initially I could not come up with a robust way of dropping on the wholerow plugin elements without tightly coupling the two plugins. 

Later on, when I figured out a way to do this, it turned out it is more user friendly not to allow drops anywhere on the node - on mobile, for example, the whole container becomes a valid drop target, and it is not possible to "cancel" the move.

But since you requested this, I thought it is about time I add this, but only enabled with a setting, so that the developer can have better control over the drops. Besides it is a good feature to have even without the wholerow plugin, although it might be a bit strange without it.

Best regards,
Ivan

**Comment by marcuspflanz** [comment]
Now that was a fast implementation.
Thanks a lot :)

Best regards,
Marcus
