### ISSUE TITLE
checkbox state *partially selected* to *not selected*

### ISSUE THREAD

**Issue by jangorecki** [vakata/jstree#973]
Hello,
Considering a list with particular selection:
![image](https://cloud.githubusercontent.com/assets/3627377/5949567/754321a8-a74f-11e4-9de6-4cb20c072cfa.png)
State of the `SubListA` can be called *partially selected*. Now if I would click on the `SubListA` with my intent to remove `SubListA` and its leafs selection but I end up with `SubListA` and all leaves selected. Normally it would not be a problem but selecting list elements triggers evaluation of functions for which more selected items means more complexity. In such case it would be much better to de-select root and leafs than selecting them.
Is there any way I can change that behavior and when clicking on partially selected root have it de-selected instead of selecting the root and leafs?
If no, is there any way to remove *partially selected* state? or maybe a FR for that :)
Thanks

**Comment by vakata** [comment]
You do not have control over the action that happens when a node is in undetermined state - it is hardcoded to select it (since the node is NOT selected, so clicking it - selects it).
The only way to modify this is to copy the checkbox plugin and create your own checkbox plugin.

As for removing the undetermined state - take a look at the checkbox plugin config options - there is an option called `three_state` - set it to `false` in your config:
```js
$('#tree').jstree({
  checkbox : {
    three_state : false
  },
  plugins : ["checkbox"]
});
```

If you want over finer control over cascading take a look at the `cascade` option.

Best regards,
Ivan

**Comment by temuri416** [comment]
@vakata 

I'd like to disable the "undetermined" visual state of the checkbox. Instead, I'd like it to render as not checked.

Is that at all possible? My config is as follows:

```js
$('#tree', this).jstree({
    plugins: ['wholerow', 'checkbox'],
    checkbox: {
        cascade: 'undetermined',
        visible: true,
        three_state: false
    }
});
```

In other words, I am trying to disable selection cascading in either direction AND I would like to undetermined state to be represented as "not checked".

Thank you!

**Comment by vakata** [comment]
@temuri416 try this: http://jsfiddle.net/DGAF4/2121/
