### ISSUE TITLE
Bug in state plugin when checkbox tie_selection is true

### ISSUE THREAD

**Issue by eDitore** [vakata/jstree#987]
At a time when checkbox plugin is on and tie_selection is set to true, state plugin does not work properly,  stores only first tree state and do nothing more.

**Comment by vakata** [comment]
Which version are you using? There was a problem in 3.0.8, which was was fixed in 3.0.9. Here is a demo showing checkbox and state plugins together, while tie_selection is at its default - true. http://jsfiddle.net/DGAF4/276/

If I misunderstood something - please let me know and I will reopen the issue.

**Comment by eDitore** [comment]
sorry I mean tie_selection is false. I have modified your example http://jsfiddle.net/DGAF4/276/ and and I have the same problem state plugin stores only first tree state and do nothing more.
